<?php
namespace EventFlow\Tests\Unit\Application\Provider;
use DateTimeImmutable;use DateTimeZone;use PHPUnit\Framework\TestCase;use EventFlow\Application\Clock\Clock;use EventFlow\Application\Job\{JobRecord,JobRepository,JobRequest,JobReconciliationResult,JobStatus};use EventFlow\Application\Persistence\EventScope;use EventFlow\Application\Provider\{NormalizedProviderWebhook,ProviderAdapter,ProviderCapabilities,ProviderDispatchMessage,ProviderEventRecord,ProviderOutcome,ProviderRegistry,ProviderRepository,ProviderSendResult,ProviderService};
final class ProviderServiceTest extends TestCase
{
 public function testWebhookIsAuthenticatedNormalizedAndDurableBeforeAck():void{$f=new ProviderFixture();$id=$f->service->ingest('mail',['signature'=>'ok'],'{"id":"evt-1"}');self::assertSame(1,$id);self::assertSame('provider.webhook.process',$f->jobs->record->jobType);self::assertSame('evt-1',$f->jobs->record->payload['native_event_key']);$again=$f->service->ingest('mail',['signature'=>'ok'],'{"id":"evt-1"}');self::assertSame($id,$again);}
 public function testAmbiguousDispatchIsRecordedAndNotReportedAsFailure():void{$f=new ProviderFixture(throwSend:true);$result=$f->service->dispatch($f->scope,5,'mail');self::assertSame(ProviderOutcome::AMBIGUOUS,$result->outcome);self::assertSame(ProviderOutcome::AMBIGUOUS,$f->repository->result->outcome);}
 public function testProcessingDedupesAndAppliesCorrelatedEvidenceOnce():void{$f=new ProviderFixture();$f->service->ingest('mail',['signature'=>'ok'],'{"id":"evt-1"}');$first=$f->service->process($f->jobs->record);$second=$f->service->process($f->jobs->record);self::assertFalse($first->duplicate);self::assertTrue($second->duplicate);self::assertSame(1,$f->repository->applied);}
 public function testDedupeAlgorithmIsVersionedAndStable():void{$e=(new ProviderFixture())->adapter->event();self::assertSame($e->dedupeKey(),$e->dedupeKey());self::assertSame(64,strlen($e->dedupeKey()));}
}
final class ProviderFixture{public EventScope $scope;public ProviderMemoryRepository $repository;public ProviderMemoryJobs $jobs;public ProviderFakeAdapter $adapter;public ProviderService $service;public function __construct(bool $throwSend=false){$this->scope=new EventScope(20);$this->repository=new ProviderMemoryRepository($this->scope);$this->jobs=new ProviderMemoryJobs();$this->adapter=new ProviderFakeAdapter($this->scope,$throwSend);$this->service=new ProviderService($this->repository,new ProviderRegistry($this->adapter),$this->jobs,new ProviderClock());}}
final class ProviderFakeAdapter implements ProviderAdapter{public function __construct(private EventScope $scope,private bool $throw=false){}public function name():string{return'mail';}public function capabilities():ProviderCapabilities{return new ProviderCapabilities(true,true,true);}public function send(ProviderDispatchMessage $m):ProviderSendResult{if($this->throw)throw new \RuntimeException('network');return new ProviderSendResult(ProviderOutcome::ACCEPTED,'pm-1',$m->requestKey);}public function authenticateAndNormalize(array $h,string $b):NormalizedProviderWebhook{if(($h['signature']??'')!=='ok')throw new \RuntimeException('auth');return $this->event();}public function event():NormalizedProviderWebhook{return new NormalizedProviderWebhook($this->scope,'mail','evt-1','pm-1',null,'delivered','delivered','delivered',null,null,new DateTimeImmutable('2026-08-16T22:00:00Z'),hash('sha256','payload'));}}
final class ProviderMemoryRepository implements ProviderRepository{public ?ProviderSendResult $result=null;public int $events=0;public int $applied=0;public function __construct(private EventScope $scope){}public function lockQueuedMessage(EventScope $s,int $id,string $p,DateTimeImmutable $n):ProviderDispatchMessage{return new ProviderDispatchMessage($s,$id,'email','a@example.test','Hi','Body',1,hash('sha256','request'));}public function recordSendResult(ProviderDispatchMessage $m,string $p,ProviderSendResult $r,DateTimeImmutable $n):void{$this->result=$r;}public function correlate(EventScope $s,string $p,?string $mid,?string $rid):?array{return['message_id'=>5,'attempt_id'=>7];}public function storeEvent(NormalizedProviderWebhook $e,int $m,?int $a,DateTimeImmutable $n):ProviderEventRecord{$this->events++;return new ProviderEventRecord(9,$m,$e->dedupeKey(),$e->normalizedType,$this->events>1);}public function applyEvent(EventScope $s,ProviderEventRecord $e,DateTimeImmutable $n):void{$this->applied++;}}
final class ProviderMemoryJobs implements JobRepository{public ?JobRecord $record=null;public function enqueue(JobRequest $r,DateTimeImmutable $at):JobRecord{if($this->record)return$this->record;return$this->record=new JobRecord(1,$r->eventScope,$r->jobType,$r->payloadVersion,$r->payload,$r->committedCapabilities,JobStatus::PENDING,$r->priority,0,$r->maxAttempts);}public function claimNext(string $o,string $t,DateTimeImmutable $n,DateTimeImmutable $e):?JobRecord{return null;}public function heartbeat(int $i,string $t,DateTimeImmutable $n,DateTimeImmutable $e):void{}public function complete(int $i,string $t,DateTimeImmutable $n):void{}public function fail(int $i,string $t,string $e,bool $d,DateTimeImmutable $f,DateTimeImmutable $a):void{}public function reconcile(DateTimeImmutable $n):JobReconciliationResult{return new JobReconciliationResult(0,0,false);}}
final readonly class ProviderClock implements Clock{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-16 22:00:00',new DateTimeZone('UTC'));}}
