<?php
namespace EventFlow\Application\CheckIn;
use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};
use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext,PrincipalType};
use EventFlow\Application\Clock\Clock;
use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};
use EventFlow\Application\Persistence\EventScope;
use EventFlow\Application\Security\SecureRandom;

final readonly class CheckInService implements ReceptionSearch, CheckInCommands
{
    public function __construct(private CheckInRepository $repository,private AuthorizationService $authorization,private IdempotencyService $idempotency,private AuditService $audit,private Clock $clock,private SecureRandom $random) {}
    public function search(PrincipalContext $principal,EventScope $scope,string $query,int $limit=20): array { $this->authorization->requireEventCapability($principal,$scope,Capability::CHECK_IN); $query=trim($query); if(strlen($query)<2 || strlen($query)>190 || $limit<1 || $limit>50) throw new CheckInException('reception_search_invalid'); return $this->repository->search($scope,$query,$limit); }
    public function lookup(PrincipalContext $principal,EventScope $scope,string $code): ReceptionAttendee { $this->authorization->requireEventCapability($principal,$scope,Capability::CHECK_IN); if(!preg_match('/^[a-f0-9]{64}$/',$code)) throw new CheckInException('reception_lookup_invalid'); return $this->repository->lookup($scope,$code) ?? throw new CheckInException('resource_not_found'); }
    public function createStation(PrincipalContext $principal,EventScope $scope,string $name,?string $code,string $key): IdempotencyOutcome { $name=trim($name); $code=$code===null?null:strtoupper(trim($code)); if($name===''||strlen($name)>190||($code!==null&&!preg_match('/^[A-Z0-9_-]{1,32}$/',$code))) throw new CheckInException('checkin_station_invalid'); return $this->idempotency->execute($principal,$scope,'checkin.station.create',$key,compact('name','code'),function()use($principal,$scope,$name,$code){$this->authorization->requireEventCapability($principal,$scope,Capability::MANAGE_SEATING);$station=$this->repository->createStation($scope,$name,$code,$this->actor($principal),$this->clock->now());$this->audit->recordRequired(new AuditEvent($principal,$scope,AuditAction::CHECKIN_STATION_CREATED,AuditEntityType::CHECKIN_STATION,$station->stationId,after:['name'=>$station->name,'code'=>$station->code]));return new IdempotentOperationResult(new IdempotencyResultReference('checkin_station',$station->stationId,201),$station);}); }
    public function checkIn(PrincipalContext $principal,EventScope $scope,int $attendeeId,?int $stationId,CheckInMethod $method,string $key,?string $notes=null): IdempotencyOutcome { return $this->bulk($principal,$scope,[$attendeeId],$stationId,$method,$key,$notes); }
    /** @param list<int> $attendeeIds */
    public function bulk(PrincipalContext $principal,EventScope $scope,array $attendeeIds,?int $stationId,CheckInMethod $method,string $key,?string $notes=null): IdempotencyOutcome
    {
        $ids=array_values(array_unique($attendeeIds));sort($ids,SORT_NUMERIC);if($ids===[]||count($ids)>100||($notes!==null&&strlen($notes)>2000))throw new CheckInException('bulk_checkin_invalid');foreach($ids as $id)if(!is_int($id)||$id<1)throw new CheckInException('bulk_checkin_invalid');
        return $this->idempotency->execute($principal,$scope,'checkin.bulk',$key,['attendee_ids'=>$ids,'station_id'=>$stationId,'method'=>$method->value,'notes'=>$notes],function()use($principal,$scope,$ids,$stationId,$method,$notes){$this->authorization->requireEventCapability($principal,$scope,Capability::CHECK_IN);if($stationId!==null&&$this->repository->lockStation($scope,$stationId)===null)throw new CheckInException('checkin_station_invalid');$attendees=$this->repository->lockAttendees($scope,$ids);if(array_map(fn($a)=>$a->attendeeId,$attendees)!==$ids)throw new CheckInException('resource_not_found');foreach($attendees as $a){if($a->attendanceStatus!=='confirmed')throw new CheckInException('attendee_not_checkin_eligible');if($a->checkedIn)throw new CheckInException('attendee_already_checked_in');}$operation=$this->uuid();$actions=[];foreach($ids as $id){$action=$this->repository->append($scope,$id,$method,$stationId,null,$operation,null,$notes,$this->actor($principal),$this->clock->now());$actions[]=$action;$this->audit->recordRequired(new AuditEvent($principal,$scope,AuditAction::CHECK_IN_RECORDED,AuditEntityType::CHECK_IN,$action->checkInId,operationId:$operation,after:['attendee_id'=>$id,'station_id'=>$stationId,'method'=>$method->value]));}$result=new BulkCheckInResult($operation,$actions);return new IdempotentOperationResult(new IdempotencyResultReference(count($actions)===1?'check_in':'checkin_operation',count($actions)===1?$actions[0]->checkInId:$scope->eventId,201),$result);});
    }
    public function reverse(PrincipalContext $principal,EventScope $scope,int $checkInId,string $reason,string $key): IdempotencyOutcome { $reason=trim($reason);if($reason===''||strlen($reason)>500)throw new CheckInException('checkin_reversal_reason_required');return $this->idempotency->execute($principal,$scope,'checkin.reverse',$key,compact('checkInId','reason'),function()use($principal,$scope,$checkInId,$reason){$this->authorization->requireEventCapability($principal,$scope,Capability::REVERSE_CHECK_IN);$original=$this->repository->lockAction($scope,$checkInId);if($original===null||$original->actionType!=='check_in')throw new CheckInException('resource_not_found');if($this->repository->reversalExists($scope,$checkInId))throw new CheckInException('checkin_already_reversed');$action=$this->repository->append($scope,$original->attendeeId,CheckInMethod::MANUAL,$original->stationId,$checkInId,null,$reason,null,$this->actor($principal),$this->clock->now());$this->audit->recordRequired(new AuditEvent($principal,$scope,AuditAction::CHECK_IN_REVERSED,AuditEntityType::CHECK_IN,$action->checkInId,before:['effective_checkin_id'=>$checkInId],after:['checked_in'=>false],reason:$reason));return new IdempotentOperationResult(new IdempotencyResultReference('check_in',$action->checkInId,201),$action);}); }
    private function actor(PrincipalContext $p):?int{return $p->type===PrincipalType::WORDPRESS_USER?$p->userId:null;}
    private function uuid():string{$h=$this->random->hex(16);return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20,12);}
}
