<?php
namespace EventFlow\Application\Provider;
use EventFlow\Application\Clock\Clock;use EventFlow\Application\Job\{JobRecord,JobRepository,JobRequest};use EventFlow\Application\Persistence\EventScope;
final readonly class ProviderService implements ProviderWebhookIngress
{
 public function __construct(private ProviderRepository $repository,private ProviderRegistry $providers,private JobRepository $jobs,private Clock $clock,private ProviderCircuitBreaker $circuitBreaker=new ClosedProviderCircuitBreaker()){}
 public function dispatch(EventScope $scope,int $messageId,string $provider):ProviderSendResult{$adapter=$this->providers->require($provider);$now=$this->clock->now();$this->circuitBreaker->assertAvailable($provider,$now);$message=$this->repository->lockQueuedMessage($scope,$messageId,$provider,$now);try{$result=$adapter->send($message);}catch(\Throwable){$result=new ProviderSendResult(ProviderOutcome::AMBIGUOUS,errorCode:'provider_transport_unknown');}$this->repository->recordSendResult($message,$provider,$result,$this->clock->now());if($result->outcome===ProviderOutcome::ACCEPTED)$this->circuitBreaker->recordSuccess($provider);elseif($result->outcome===ProviderOutcome::AMBIGUOUS)$this->circuitBreaker->recordFailure($provider,$this->clock->now());return $result;}
 /** Durable job insertion completes before the caller may acknowledge the webhook. @param array<string,string> $headers */
 public function ingest(string $provider,array $headers,string $rawBody):int{if(strlen($rawBody)>1048576)throw new ProviderException('provider_webhook_too_large');$event=$this->providers->require($provider)->authenticateAndNormalize($headers,$rawBody);if($event->provider!==$provider)throw new ProviderException('provider_webhook_invalid');$job=$this->jobs->enqueue(JobRequest::create($event->eventScope,'provider.webhook.process',1,$event->jobPayload(),[],$this->clock->now(),20,20,$provider.':'.$event->dedupeKey()),$this->clock->now());return $job->jobId;}
 public function process(JobRecord $job):ProviderEventRecord{if($job->jobType!=='provider.webhook.process'||$job->eventScope===null)throw new ProviderException('provider_webhook_job_invalid');$p=$job->payload;$event=new NormalizedProviderWebhook($job->eventScope,(string)$p['provider'],$p['native_event_key'], $p['provider_message_id'],$p['provider_request_id'],(string)$p['provider_event_type'],(string)$p['normalized_type'],$p['provider_status'],$p['reason_code'],$p['reason_message'],$p['occurred_at']===null?null:new \DateTimeImmutable($p['occurred_at']),(string)$p['payload_hash']);$correlation=$this->repository->correlate($job->eventScope,$event->provider,$event->providerMessageId,$event->providerRequestId);if($correlation===null)throw new ProviderException('provider_event_unmatched');$record=$this->repository->storeEvent($event,(int)$correlation['message_id'],isset($correlation['attempt_id'])?(int)$correlation['attempt_id']:null,$this->clock->now());if(!$record->duplicate)$this->repository->applyEvent($job->eventScope,$record,$this->clock->now());return $record;}
}
