<?php
namespace EventFlow\Tests\Unit\Application\Communication;
require_once __DIR__.'/TemplateAccessServiceTest.php';
use DateTimeImmutable;use DateTimeZone;use EventFlow\Application\Audit\{AuditCanonicalizer,AuditPayloadRedactor,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,PrincipalContext,RoleCapabilityPolicy};use EventFlow\Application\Communication\{AudienceMode,CampaignAccessRepository,CampaignAccessService,CampaignPage,CampaignPurpose,CampaignRecipient,CampaignRecord,CampaignReplacement,CommunicationChannel,CommunicationException,TemplateRecord};use EventFlow\Application\Idempotency\{CanonicalRequestHasher,IdempotencyService};use EventFlow\Application\Persistence\EventScope;use PHPUnit\Framework\TestCase;
final class CampaignAccessServiceTest extends TestCase
{
 public function testReadsUpdatePreviewScheduleAndCancelAreAuthoritative():void{$scope=new EventScope(9);$principal=PrincipalContext::wordpressUser(7);$repo=new CampaignMemoryRepository();$service=$this->service($repo);self::assertSame(21,$service->list($principal,$scope)->campaigns[0]->campaignId);self::assertSame('Draft',$service->read($principal,$scope,21)->name);$r=new CampaignReplacement(11,' Updated ',CommunicationChannel::EMAIL,CampaignPurpose::REMINDER,AudienceMode::DYNAMIC,['filter'=>'active_invitations','invitation_ids'=>[2,1,2]],1);$updated=$service->update($principal,$scope,21,$r,'campaign-update-001')->response;self::assertSame('Updated',$updated->name);self::assertSame([1,2],$updated->audienceDefinition['invitation_ids']);self::assertSame(2,$updated->revision);$preview=$service->audiencePreview($principal,$scope,21);self::assertSame(2,$preview->recipientCount);self::assertMatchesRegularExpression('/^[a-f0-9]{64}$/',$preview->audienceFingerprint);$scheduled=$service->schedule($principal,$scope,22,1,new DateTimeImmutable('2026-08-21 01:00:00',new DateTimeZone('UTC')),'campaign-schedule-001')->response;self::assertSame('scheduled',$scheduled->status);$cancelled=$service->cancel($principal,$scope,22,2,'campaign-cancel-001')->response;self::assertSame('cancelled',$cancelled->status);self::assertNotNull($cancelled->cancelledAt);}
 public function testLifecycleRejectsStalePastAndQueuedCampaigns():void{$s=new EventScope(9);$p=PrincipalContext::wordpressUser(7);$service=$this->service(new CampaignMemoryRepository());foreach([fn()=> $service->schedule($p,$s,21,1,new DateTimeImmutable('2026-08-19',new DateTimeZone('UTC')),'campaign-past-001'),fn()=> $service->cancel($p,$s,21,9,'campaign-stale-001'),fn()=> $service->cancel($p,$s,23,1,'campaign-queued-001')]as$o){try{$o();self::fail('Expected failure.');}catch(CommunicationException$e){self::assertContains($e->safeCode,['campaign_schedule_invalid','resource_modified','campaign_transition_invalid']);}}}
 private function service(CampaignAccessRepository$r):CampaignAccessService{$clock=new TemplateClock();$tx=new TemplateTransactions();return new CampaignAccessService($r,new AuthorizationService(new TemplateMemberships(),new RoleCapabilityPolicy(),$clock,new TemplateRecovery()),new IdempotencyService(new TemplateIdempotency(),$tx,$clock,new TemplateRandom(),new CanonicalRequestHasher()),new AuditService(new TemplateAudit(),$tx,$clock,new AuditPayloadRedactor(),new AuditCanonicalizer()),$clock);}
}
final class CampaignMemoryRepository implements CampaignAccessRepository
{public array$records;public function __construct(){$this->records=[21=>$this->record(21,'draft','Draft'),22=>$this->record(22,'draft','Schedule'),23=>$this->record(23,'queued','Queued')];}public function listCampaigns(EventScope$s,int$l,?int$a):CampaignPage{return new CampaignPage(array_values($this->records),null);}public function findCampaign(EventScope$s,int$id):?CampaignRecord{return$this->records[$id]??null;}public function lockCampaignRecord(EventScope$s,int$id):?CampaignRecord{return$this->findCampaign($s,$id);}public function updateCampaign(EventScope$s,CampaignRecord$c,CampaignReplacement$r,int$a,DateTimeImmutable$n):CampaignRecord{return$this->records[$c->campaignId]=new CampaignRecord($c->campaignId,$r->templateId,$r->name,$r->channel,$r->purpose,$r->audienceMode,$r->audience,'draft',$c->revision+1);}public function scheduleCampaign(EventScope$s,CampaignRecord$c,DateTimeImmutable$at,int$a,DateTimeImmutable$n):CampaignRecord{return$this->records[$c->campaignId]=new CampaignRecord($c->campaignId,$c->templateId,$c->name,$c->channel,$c->purpose,$c->audienceMode,$c->audienceDefinition,'scheduled',$c->revision+1,$at);}public function cancelCampaign(EventScope$s,CampaignRecord$c,int$a,DateTimeImmutable$n):CampaignRecord{return$this->records[$c->campaignId]=new CampaignRecord($c->campaignId,$c->templateId,$c->name,$c->channel,$c->purpose,$c->audienceMode,$c->audienceDefinition,'cancelled',$c->revision+1,$c->scheduledAt,null,null,$n);}public function publishedTemplate(EventScope$s,int$id):?TemplateRecord{return new TemplateRecord(11,'reminder','Reminder',CommunicationChannel::EMAIL,1,'published',null,'Body',null,[]);}public function previewRecipients(EventScope$s,CampaignRecord$c):array{return[new CampaignRecipient(1,null,'A','a@example.test',[]),new CampaignRecipient(2,5,'B','b@example.test',[])];}private function record(int$id,string$status,string$name):CampaignRecord{return new CampaignRecord($id,11,$name,CommunicationChannel::EMAIL,CampaignPurpose::REMINDER,AudienceMode::DYNAMIC,['mode'=>'dynamic','filter'=>'active_invitations','invitation_ids'=>[]],$status);}}
