<?php
namespace EventFlow\Tests\Unit\Application\Communication;
require_once __DIR__.'/CampaignAccessServiceTest.php';
use DateTimeImmutable;use EventFlow\Application\Audit\{AuditCanonicalizer,AuditPayloadRedactor,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext,RoleCapabilityPolicy};use EventFlow\Application\Communication\{CommunicationChannel,CommunicationException,MessageAccessRepository,MessageAccessService,MessagePage,MessageRecord,MessageRetryResult};use EventFlow\Application\Idempotency\{CanonicalRequestHasher,IdempotencyService};use EventFlow\Application\Job\{JobRecord,JobRepository,JobRequest,JobReconciliationResult,JobStatus};use EventFlow\Application\Persistence\EventScope;use PHPUnit\Framework\TestCase;
final class MessageAccessServiceTest extends TestCase
{
public function testQueriesAndRetryCreateDurableLeastPrivilegeJob():void{$repo=new MessageMemoryRepository();$jobs=new MessageMemoryJobs();$service=$this->service($repo,$jobs);$scope=new EventScope(9);$principal=PrincipalContext::wordpressUser(7);$page=$service->list($principal,$scope,25,10,21,'failed');self::assertSame([25,10,21,'failed'],$repo->query);self::assertSame(61,$page->messages[0]->messageId);self::assertSame('a@example.test',$service->read($principal,$scope,61)->recipientAddress);$outcome=$service->retry($principal,$scope,61,3,'message-retry-001');self::assertSame(202,$outcome->reference->responseStatusCode);self::assertInstanceOf(MessageRetryResult::class,$outcome->response);self::assertSame('retry_pending',$outcome->response->message->status);self::assertSame(4,$outcome->response->message->revision);self::assertSame('message.delivery.retry',$jobs->record?->jobType);self::assertSame(['message_id'=>61,'provider'=>'brevo'],$jobs->record?->payload);self::assertSame([Capability::QUEUE_CAMPAIGN],$jobs->record?->committedCapabilities);}
 public function testInvalidFiltersStaleAndNonRetryableMessagesFailClosed():void{$scope=new EventScope(9);$p=PrincipalContext::wordpressUser(7);foreach([fn()=> $this->service(new MessageMemoryRepository(),new MessageMemoryJobs())->list($p,$scope,101,status:'failed'),fn()=> $this->service(new MessageMemoryRepository(),new MessageMemoryJobs())->list($p,$scope,status:'secret'),fn()=> $this->service(new MessageMemoryRepository(),new MessageMemoryJobs())->retry($p,$scope,61,2,'message-stale-001'),fn()=> $this->service(new MessageMemoryRepository('delivered'),new MessageMemoryJobs())->retry($p,$scope,61,3,'message-final-001')]as$operation){try{$operation();self::fail('Expected failure.');}catch(CommunicationException$e){self::assertContains($e->safeCode,['message_query_invalid','resource_modified','message_not_retryable']);}}}
 private function service(MessageAccessRepository$r,JobRepository$j):MessageAccessService{$clock=new TemplateClock();$tx=new TemplateTransactions();return new MessageAccessService($r,$j,new AuthorizationService(new TemplateMemberships(),new RoleCapabilityPolicy(),$clock,new TemplateRecovery()),new IdempotencyService(new TemplateIdempotency(),$tx,$clock,new TemplateRandom(),new CanonicalRequestHasher()),new AuditService(new TemplateAudit(),$tx,$clock,new AuditPayloadRedactor(),new AuditCanonicalizer()),$clock);}
}
final class MessageMemoryRepository implements MessageAccessRepository
{public array$query=[];private MessageRecord$record;public function __construct(string$status='failed'){$this->record=$this->make($status,3);}public function listMessages(EventScope$s,int$l,?int$a,?int$c,?string$status):MessagePage{$this->query=[$l,$a,$c,$status];return new MessagePage([$this->record],null);}public function findMessage(EventScope$s,int$id):?MessageRecord{return$id===61?$this->record:null;}public function lockMessage(EventScope$s,int$id):?MessageRecord{return$this->findMessage($s,$id);}public function markRetryPending(EventScope$s,MessageRecord$c,DateTimeImmutable$n):MessageRecord{return$this->record=$this->make('retry_pending',$c->revision+1);}private function make(string$status,int$revision):MessageRecord{return new MessageRecord(61,21,hash('sha256','logical'),'a@example.test','Subject','Rendered',CommunicationChannel::EMAIL,$status,$revision,11,12,'Guest','Plain','mail','pm-1',2);}}
final class MessageMemoryJobs implements JobRepository
{public ?JobRecord$record=null;public function enqueue(JobRequest$r,DateTimeImmutable$at):JobRecord{return$this->record??=$this->make($r);}private function make(JobRequest$r):JobRecord{return new JobRecord(91,$r->eventScope,$r->jobType,$r->payloadVersion,$r->payload,$r->committedCapabilities,JobStatus::PENDING,$r->priority,0,$r->maxAttempts);}public function claimNext(string$o,string$t,DateTimeImmutable$n,DateTimeImmutable$e):?JobRecord{return null;}public function heartbeat(int$i,string$t,DateTimeImmutable$n,DateTimeImmutable$e):void{}public function complete(int$i,string$t,DateTimeImmutable$n):void{}public function fail(int$i,string$t,string$e,bool$d,DateTimeImmutable$f,DateTimeImmutable$a):void{}public function reconcile(DateTimeImmutable$n):JobReconciliationResult{return new JobReconciliationResult(0,0,false);}}
