<?php
namespace EventFlow\Tests\Unit\Application\Import;
require_once __DIR__.'/ImportServiceTest.php';
use DateTimeImmutable;use EventFlow\Application\Audit\{AuditCanonicalizer,AuditPayloadRedactor,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext,RoleCapabilityPolicy};use EventFlow\Application\Idempotency\{CanonicalRequestHasher,IdempotencyService};use EventFlow\Application\Import\{ImportAdministrationRepository,ImportAdministrationService,ImportApplyRequest,ImportException,ImportJobPage,ImportJobRecord,ImportResult,ImportRowPage,ImportRowRecord,ImportRowStatus,ImportStatus};use EventFlow\Application\Job\{JobRecord,JobRepository,JobRequest,JobReconciliationResult,JobStatus};use EventFlow\Application\Persistence\EventScope;use PHPUnit\Framework\TestCase;
final class ImportAdministrationServiceTest extends TestCase
{
 public function testQueriesResultsApplyAndCancelAreAuthoritative():void{$repo=new ImportAdminMemory();$jobs=new ImportAdminJobs();$service=$this->service($repo,$jobs);$scope=new EventScope(100);$p=PrincipalContext::wordpressUser(7);self::assertSame(71,$service->list($p,$scope,25,10,ImportStatus::VALIDATED)->jobs[0]->jobId);self::assertSame([25,10,ImportStatus::VALIDATED],$repo->query);self::assertSame(1,$service->rows($p,$scope,71,20)->rows[0]->sourceRowNumber);$result=$service->result($p,$scope,71);self::assertInstanceOf(ImportResult::class,$result);self::assertSame(14,$result->readyRows);$apply=$service->requestApply($p,$scope,71,3,'import-apply-001')->response;self::assertInstanceOf(ImportApplyRequest::class,$apply);self::assertSame('applying',$apply->job->status->value);self::assertSame(4,$apply->job->revision);self::assertSame('import.apply',$jobs->record?->jobType);self::assertSame(['import_job_id'=>71],$jobs->record?->payload);self::assertSame([Capability::MANAGE_IMPORTS],$jobs->record?->committedCapabilities);$cancelRepo=new ImportAdminMemory(ImportStatus::STAGED);$cancelled=$this->service($cancelRepo,new ImportAdminJobs())->cancel($p,$scope,71,3,'import-cancel-001')->response;self::assertSame(ImportStatus::CANCELLED,$cancelled->status);self::assertNotNull($cancelled->cancelledAt);}
 public function testBoundsStaleAndFinalTransitionsFailClosed():void{$scope=new EventScope(100);$p=PrincipalContext::wordpressUser(7);foreach([fn()=> $this->service(new ImportAdminMemory(),new ImportAdminJobs())->list($p,$scope,0),fn()=> $this->service(new ImportAdminMemory(),new ImportAdminJobs())->requestApply($p,$scope,71,2,'import-stale-001'),fn()=> $this->service(new ImportAdminMemory(ImportStatus::COMPLETED),new ImportAdminJobs())->cancel($p,$scope,71,3,'import-final-001')]as$operation){try{$operation();self::fail('Expected failure.');}catch(ImportException$e){self::assertContains($e->safeCode,['import_query_invalid','resource_modified','import_transition_invalid']);}}}
 private function service(ImportAdministrationRepository$r,JobRepository$j):ImportAdministrationService{$clock=new ImportClock();$tx=new ImportTransactions();return new ImportAdministrationService($r,$j,new AuthorizationService(new ImportMembershipReader(),new RoleCapabilityPolicy(),$clock,new ImportNoRecovery()),new IdempotencyService(new ImportIdempotencyRepository(),$tx,$clock,new ImportRandom(),new CanonicalRequestHasher()),new AuditService(new ImportAuditRepository(),$tx,$clock,new AuditPayloadRedactor(),new AuditCanonicalizer()),$clock);}
}
final class ImportAdminMemory implements ImportAdministrationRepository
{public array$query=[];public ImportJobRecord$job;public function __construct(ImportStatus$status=ImportStatus::VALIDATED){$this->job=$this->make($status,3);}public function listJobs(EventScope$s,int$l,?int$a,?ImportStatus$status):ImportJobPage{$this->query=[$l,$a,$status];return new ImportJobPage([$this->job],null);}public function findJob(EventScope$s,int$id):?ImportJobRecord{return$id===71?$this->job:null;}public function listRows(EventScope$s,int$id,int$l,?int$a,?ImportRowStatus$status):ImportRowPage{return new ImportRowPage([new ImportRowRecord(81,71,1,ImportRowStatus::READY,['Name'=>'Guest'],['primary_name'=>'Guest'])],null);}public function markApplyQueued(EventScope$s,ImportJobRecord$c,DateTimeImmutable$n):ImportJobRecord{return$this->job=$this->make(ImportStatus::APPLYING,$c->revision+1);}public function cancelJob(EventScope$s,ImportJobRecord$c,DateTimeImmutable$n):ImportJobRecord{return$this->job=$this->make(ImportStatus::CANCELLED,$c->revision+1,$n);}private function make(ImportStatus$status,int$revision,?DateTimeImmutable$cancelled=null):ImportJobRecord{return new ImportJobRecord(71,new EventScope(100),$status,'guests.csv',hash('sha256','file'),20,17,2,1,2,revision:$revision,warningRows:1,skippedRows:0,mapping:['primary_name'=>'Name'],cancelledAt:$cancelled);}}
final class ImportAdminJobs implements JobRepository
{public ?JobRecord$record=null;public function enqueue(JobRequest$r,DateTimeImmutable$n):JobRecord{return$this->record??=new JobRecord(91,$r->eventScope,$r->jobType,$r->payloadVersion,$r->payload,$r->committedCapabilities,JobStatus::PENDING,$r->priority,0,$r->maxAttempts);}public function claimNext(string$o,string$t,DateTimeImmutable$n,DateTimeImmutable$e):?JobRecord{return null;}public function heartbeat(int$i,string$t,DateTimeImmutable$n,DateTimeImmutable$e):void{}public function complete(int$i,string$t,DateTimeImmutable$n):void{}public function fail(int$i,string$t,string$e,bool$d,DateTimeImmutable$f,DateTimeImmutable$a):void{}public function reconcile(DateTimeImmutable$n):JobReconciliationResult{return new JobReconciliationResult(0,0,false);}}
