<?php
namespace EventFlow\Tests\Integration;
use EventFlow\Application\Import\{ImportAdministration,ImportAdministrationService,ImportApplyRequest,ImportJobPage,ImportJobRecord,ImportResult,ImportRowPage};use PHPUnit\Framework\TestCase;
final class Sprint10ImportAdministrationContractTest extends TestCase
{
 public function testContractsRepositorySchemaAndFoundationAreComposed():void{self::assertContains(ImportAdministration::class,class_implements(ImportAdministrationService::class));foreach([ImportJobPage::class,ImportRowPage::class,ImportResult::class,ImportApplyRequest::class]as$class)self::assertTrue(class_exists($class));self::assertTrue(property_exists(ImportJobRecord::class,'revision'));$repo=$this->source('src/Infrastructure/Persistence/WordPress/WpdbImportRepository.php');foreach(['ImportAdministrationRepository','listJobs','findJob','listRows','markApplyQueued','cancelJob','import_revision=import_revision+1']as$x)self::assertStringContainsString($x,$repo);$migration=$this->source('database/migrations/0015-import-administration.sql');foreach(['import_revision','cancelled_at','CHECK (import_revision >= 1)']as$x)self::assertStringContainsString($x,$migration);self::assertStringContainsString("define('EVENTFLOW_SCHEMA_VERSION', 15);",$this->source('eventflow.php'));$foundation=$this->source('src/Bootstrap/DatabaseFoundation.php');self::assertStringContainsString('public ImportAdministrationService $importAdministration',$foundation);}
 public function testAuthorizationJobsAuditConcurrencyAndHttpDeferralAreExplicit():void{$service=$this->source('src/Application/Import/ImportAdministrationService.php');foreach(['Capability::MANAGE_IMPORTS',"'import.apply.request'","'import.cancel'","'import.apply'",'JobRequest::create','resource_modified','AuditAction::IMPORT_APPLY_REQUESTED','AuditAction::IMPORT_CANCELLED']as$x)self::assertStringContainsString($x,$service);$readme=$this->source('README-IMP-069.md');self::assertStringContainsString('intentionally adds no HTTP routes',$readme);self::assertStringContainsString('IMP-070',$readme);self::assertStringContainsString('hardened upload',$readme);}
 private function source(string$r):string{$contents=file_get_contents(dirname(__DIR__,2).'/'.$r);self::assertIsString($contents);return$contents;}
}
