<?php
namespace EventFlow\Tests\Integration;
use EventFlow\Application\Communication\{MessageAccess,MessageAccessService,MessagePage,MessageRecord,MessageRetryResult};use PHPUnit\Framework\TestCase;
final class Sprint10MessageAccessContractTest extends TestCase
{
 public function testContractsRepositoryAndSchemaAreComposed():void{self::assertContains(MessageAccess::class,class_implements(MessageAccessService::class));self::assertTrue(property_exists(MessagePage::class,'nextAfterMessageId'));self::assertTrue(property_exists(MessageRecord::class,'revision'));self::assertTrue(property_exists(MessageRetryResult::class,'jobId'));$repo=$this->source('src/Infrastructure/Persistence/WordPress/WpdbCommunicationRepository.php');foreach(['MessageAccessRepository','listMessages','lockMessage','markRetryPending',"delivery_status='retry_pending'",'message_revision=message_revision+1']as$x)self::assertStringContainsString($x,$repo);$migration=$this->source('database/migrations/0014-message-revision.sql');self::assertStringContainsString('message_revision',$migration);self::assertStringNotContainsString('DROP ',$migration);self::assertMatchesRegularExpression("/define\\('EVENTFLOW_SCHEMA_VERSION', (?:1[4-9]|[2-9][0-9]+)\\);/",$this->source('eventflow.php'));}
 public function testAuthorizationRetryJobAuditAndHttpDeferralAreExplicit():void{$service=$this->source('src/Application/Communication/MessageAccessService.php');foreach(['Capability::QUEUE_CAMPAIGN',"'message.retry'",'message_not_retryable',"'message.delivery.retry'",'JobRequest::create','AuditAction::MESSAGE_RETRY_REQUESTED','AuditEntityType::MESSAGE']as$x)self::assertStringContainsString($x,$service);$provider=$this->source('src/Infrastructure/Persistence/WordPress/WpdbProviderRepository.php');self::assertGreaterThanOrEqual(3,substr_count($provider,'message_revision=message_revision+1'));$foundation=$this->source('src/Bootstrap/DatabaseFoundation.php');self::assertStringContainsString('public MessageAccessService $messageAccess',$foundation);self::assertStringContainsString('$jobRepository',$foundation);$readme=$this->source('README-IMP-067.md');self::assertStringContainsString('intentionally adds no HTTP routes',$readme);self::assertStringContainsString('IMP-068',$readme);}
 private function source(string$r):string{$root=dirname(__DIR__,2);$contents=file_get_contents($root.'/'.$r);self::assertIsString($contents);return$contents;}
}
