<?php
namespace EventFlow\Tests\Integration;
use PHPUnit\Framework\TestCase;
final class Sprint10MessageAccessDeliveryTest extends TestCase
{
 public function testRoutesAreCompleteAndReadyModeBootstrapped():void{$routes=$this->source('src/Presentation/Api/MessageAccessRouteRegistrar.php');self::assertSame(2,substr_count($routes,'registerAuthenticatedGet'));self::assertSame(1,substr_count($routes,'registerAuthenticatedPost'));self::assertStringContainsString('/retry',$routes);$bootstrap=$this->source('src/Bootstrap/ApplicationBootstrap.php');$ready=strpos($bootstrap,'if ($bootstrap->ready && $container->database !== null)');$registration=strpos($bootstrap,'new MessageAccessRouteRegistrar(');self::assertNotFalse($ready);self::assertNotFalse($registration);self::assertGreaterThan($ready,$registration);self::assertStringContainsString('$container->database->messageAccess',$bootstrap);}
 public function testPreconditionsFiltersPrivacyAndResponseContractsAreExplicit():void{$controller=$this->source('src/Presentation/Api/MessageAccessController.php');self::assertSame(2,substr_count($controller,'MutationPreconditionPolicy::NONE'));self::assertSame(1,substr_count($controller,'MutationPreconditionPolicy::IF_MATCH_AND_IDEMPOTENCY_KEY'));self::assertStringContainsString('requireEmptyBody',$controller);$mapper=$this->source('src/Presentation/Api/MessageAccessRequestMapper.php');foreach(["'campaign_id'","'status'","'limit'","'after'"]as$field)self::assertStringContainsString($field,$mapper);$presenter=$this->source('src/Presentation/Api/MessageAccessPresenter.php');foreach(["'retry_job_id'","'ETag'","'Cache-Control'=>'no-store, max-age=0'",'private function summary','private function detail']as$field)self::assertStringContainsString($field,$presenter);$summary=substr($presenter,strpos($presenter,'private function summary'),strpos($presenter,'private function detail')-strpos($presenter,'private function summary'));self::assertStringNotContainsString("'content'",$summary);self::assertStringNotContainsString("'plain_text'",$summary);$readme=$this->source('README-IMP-068.md');self::assertStringContainsString('omit rendered and plain-text bodies',$readme);}
 private function source(string$r):string{$contents=file_get_contents(dirname(__DIR__,2).'/'.$r);self::assertIsString($contents);return$contents;}
}
