<?php
namespace EventFlow\Application\Import;
use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext};use EventFlow\Application\Clock\Clock;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};use EventFlow\Application\Job\{JobRepository,JobRequest};use EventFlow\Application\Persistence\EventScope;
final readonly class ImportAdministrationService implements ImportAdministration
{
 public function __construct(private ImportAdministrationRepository$imports,private JobRepository$jobs,private AuthorizationService$authorization,private IdempotencyService$idempotency,private AuditService$audit,private Clock$clock){}
 public function list(PrincipalContext$p,EventScope$s,int$l=50,?int$a=null,?ImportStatus$status=null):ImportJobPage{$this->authorize($p,$s);if($l<1||$l>100||($a!==null&&$a<1))throw new ImportException('import_query_invalid');return$this->imports->listJobs($s,$l,$a,$status);}
 public function read(PrincipalContext$p,EventScope$s,int$id):ImportJobRecord{$this->authorize($p,$s);return$this->imports->findJob($s,$id)??throw new ImportException('import_job_not_found');}
 public function rows(PrincipalContext$p,EventScope$s,int$id,int$l=100,?int$a=null,?ImportRowStatus$status=null):ImportRowPage{$this->authorize($p,$s);if($l<1||$l>500||($a!==null&&$a<1))throw new ImportException('import_query_invalid');$this->imports->findJob($s,$id)??throw new ImportException('import_job_not_found');return$this->imports->listRows($s,$id,$l,$a,$status);}
 public function result(PrincipalContext$p,EventScope$s,int$id):ImportResult{$job=$this->read($p,$s,$id);return new ImportResult($id,$job->status,$job->totalRows,max(0,$job->validRows-$job->appliedRows-$job->failedRows),$job->warningRows,$job->invalidRows,$job->appliedRows,$job->skippedRows,$job->failedRows);}
 public function requestApply(PrincipalContext$p,EventScope$s,int$id,int$r,string$key):IdempotencyOutcome{return$this->idempotency->execute($p,$s,'import.apply.request',$key,['import_job_id'=>$id,'expected_revision'=>$r],function()use($p,$s,$id,$r){$this->authorize($p,$s);$current=$this->required($s,$id,$r,[ImportStatus::VALIDATED]);$now=$this->clock->now();$queued=$this->imports->markApplyQueued($s,$current,$now);$job=$this->jobs->enqueue(JobRequest::create($s,'import.apply',1,['import_job_id'=>$id],[Capability::MANAGE_IMPORTS],$now,30,10,'import:'.$id.':apply:'.$queued->revision),$now);$this->audit($p,$s,$current,$queued,AuditAction::IMPORT_APPLY_REQUESTED,['worker_job_id'=>$job->jobId]);return new IdempotentOperationResult(new IdempotencyResultReference('import_job',$id,202),new ImportApplyRequest($queued,$job->jobId));});}
 public function cancel(PrincipalContext$p,EventScope$s,int$id,int$r,string$key):IdempotencyOutcome{return$this->idempotency->execute($p,$s,'import.cancel',$key,['import_job_id'=>$id,'expected_revision'=>$r],function()use($p,$s,$id,$r){$this->authorize($p,$s);$current=$this->required($s,$id,$r,[ImportStatus::UPLOADED,ImportStatus::STAGED,ImportStatus::VALIDATED]);$cancelled=$this->imports->cancelJob($s,$current,$this->clock->now());$this->audit($p,$s,$current,$cancelled,AuditAction::IMPORT_CANCELLED);return new IdempotentOperationResult(new IdempotencyResultReference('import_job',$id,200),$cancelled);});}
 private function authorize(PrincipalContext$p,EventScope$s):void{$this->authorization->requireEventCapability($p,$s,Capability::MANAGE_IMPORTS);}
 /** @param list<ImportStatus> $allowed */private function required(EventScope$s,int$id,int$r,array$allowed):ImportJobRecord{$job=$this->imports->findJob($s,$id)??throw new ImportException('import_job_not_found');if($r<1||$job->revision!==$r)throw new ImportException('resource_modified');if(!in_array($job->status,$allowed,true))throw new ImportException('import_transition_invalid');return$job;}
 /** @param array<string,mixed> $extra */private function audit(PrincipalContext$p,EventScope$s,ImportJobRecord$b,ImportJobRecord$a,AuditAction$action,array$extra=[]):void{$this->audit->recordRequired(new AuditEvent($p,$s,$action,AuditEntityType::IMPORT_JOB,$a->jobId,before:['status'=>$b->status->value,'revision'=>$b->revision],after:['status'=>$a->status->value,'revision'=>$a->revision,...$extra]));}
}
