<?php
namespace EventFlow\Infrastructure\Export;
use EventFlow\Application\Export\{ExportArtifactReader,ExportArtifactStorage,ExportDownloadGrant,ExportException,ExportFormat,ExportRecord,PublishedExportArtifact};use EventFlow\Application\Security\SecureRandom;
final readonly class WordPressProtectedExportStorage implements ExportArtifactStorage, ExportArtifactReader
{
 public function __construct(private SecureRandom $random,private ?string $baseDirectory=null){}
 public function publish(ExportRecord $export,iterable $rows):PublishedExportArtifact{$base=$this->base();$event=$base.DIRECTORY_SEPARATOR.'event-'.$export->eventScope->eventId;if(!is_dir($event)&&!mkdir($event,0700,true)&&!is_dir($event))throw new ExportException('export_storage_unavailable');$this->protect($base);$name='export-'.$export->exportId.'-'.$this->random->hex(16).'.'.$export->format->value;$final=$event.DIRECTORY_SEPARATOR.$name;$temp=$final.'.tmp';$handle=fopen($temp,'xb');if($handle===false)throw new ExportException('export_storage_unavailable');$hash=hash_init('sha256');$bytes=0;$header=false;try{foreach($rows as$row){if(!is_array($row))throw new ExportException('export_row_invalid');if($export->format===ExportFormat::CSV){$stream=fopen('php://temp','w+b');if($stream===false)throw new ExportException('export_generation_failed');if(!$header){fputcsv($stream,array_keys($row),',','"','\\');$header=true;}fputcsv($stream,array_values($row),',','"','\\');rewind($stream);$chunk=(string)stream_get_contents($stream);fclose($stream);}else{$chunk=json_encode($row,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)."\n";}if(fwrite($handle,$chunk)!==strlen($chunk))throw new ExportException('export_write_failed');hash_update($hash,$chunk);$bytes+=strlen($chunk);}fflush($handle);if(function_exists('fsync'))fsync($handle);fclose($handle);if(!rename($temp,$final))throw new ExportException('export_publish_failed');chmod($final,0600);return new PublishedExportArtifact('event-'.$export->eventScope->eventId.'/'.$name,hash_final($hash),$export->format->mimeType(),$bytes);}catch(\Throwable $e){if(is_resource($handle))fclose($handle);if(is_file($temp))unlink($temp);throw $e;}}
 public function delete(string $locator):void{if(!preg_match('/^event-[1-9][0-9]*\/export-[1-9][0-9]*-[a-f0-9]{32}\.(?:csv|jsonl)$/',$locator))throw new ExportException('export_locator_invalid');$base=realpath($this->base());$path=$this->base().DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$locator);$parent=realpath(dirname($path));if($base===false||$parent===false||!str_starts_with($parent,$base.DIRECTORY_SEPARATOR))throw new ExportException('export_locator_invalid');if(is_file($path)&&!unlink($path))throw new ExportException('export_delete_failed');}
 public function read(ExportDownloadGrant $grant):string{$expectedMime=str_ends_with($grant->locator,'.csv')?'text/csv':(str_ends_with($grant->locator,'.jsonl')?'application/x-ndjson':null);if($expectedMime!==$grant->mimeType)throw new ExportException('export_artifact_integrity_failed');$path=$this->path($grant->locator);if(is_link($path)||!is_file($path)||!is_readable($path))throw new ExportException('export_not_downloadable');$size=filesize($path);$hash=hash_file('sha256',$path);if($size===false||$size!==$grant->sizeBytes||!is_string($hash)||!hash_equals($grant->sha256,$hash))throw new ExportException('export_artifact_integrity_failed');$contents=file_get_contents($path);if(!is_string($contents)||strlen($contents)!==$grant->sizeBytes)throw new ExportException('export_artifact_read_failed');return$contents;}
 private function path(string$locator):string{if(!preg_match('/^event-[1-9][0-9]*\/export-[1-9][0-9]*-[a-f0-9]{32}\.(?:csv|jsonl)$/',$locator))throw new ExportException('export_locator_invalid');$base=realpath($this->base());$candidate=$this->base().DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$locator);$path=realpath($candidate);if($base===false||$path===false||!str_starts_with($path,$base.DIRECTORY_SEPARATOR))throw new ExportException('export_locator_invalid');return$path;}
 private function base():string{$configured=$this->baseDirectory??(defined('EVENTFLOW_PROTECTED_EXPORT_DIR')?(string)constant('EVENTFLOW_PROTECTED_EXPORT_DIR'):(defined('WP_CONTENT_DIR')?(string)constant('WP_CONTENT_DIR').DIRECTORY_SEPARATOR.'eventflow-private-exports':sys_get_temp_dir().DIRECTORY_SEPARATOR.'eventflow-private-exports'));return rtrim($configured,"/\\");}
 private function protect(string $base):void{foreach(['.htaccess'=>"Deny from all\n",'index.php'=>"<?php http_response_code(404);\n"]as$file=>$content){$path=$base.DIRECTORY_SEPARATOR.$file;if(!is_file($path)&&file_put_contents($path,$content,LOCK_EX)===false)throw new ExportException('export_storage_unavailable');}}
}
