<?php
namespace EventFlow\Application\Communication;
use DateTimeImmutable;use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext,PrincipalType};use EventFlow\Application\Clock\Clock;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};use EventFlow\Application\Persistence\EventScope;
final readonly class CampaignAccessService implements CampaignAccess
{
 public function __construct(private CampaignAccessRepository $campaigns,private AuthorizationService $authorization,private IdempotencyService $idempotency,private AuditService $audit,private Clock $clock){}
 public function list(PrincipalContext$p,EventScope$s,int$limit=50,?int$afterCampaignId=null):CampaignPage{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);if($limit<1||$limit>100||($afterCampaignId!==null&&$afterCampaignId<1))throw new CommunicationException('validation_failed');return$this->campaigns->listCampaigns($s,$limit,$afterCampaignId);}
 public function read(PrincipalContext$p,EventScope$s,int$id):CampaignRecord{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);return$this->campaigns->findCampaign($s,$id)??throw new CommunicationException('resource_not_found');}
 public function update(PrincipalContext$p,EventScope$s,int$id,CampaignReplacement$r,string$key):IdempotencyOutcome{$audience=$this->audience($r->audience,$r->audienceMode);$normalized=new CampaignReplacement($r->templateId,trim($r->name),$r->channel,$r->purpose,$r->audienceMode,$audience,$r->expectedRevision);if($normalized->name===''||strlen($normalized->name)>190)throw new CommunicationException('campaign_invalid');return$this->idempotency->execute($p,$s,'campaign.update',$key,['campaign_id'=>$id,...$this->canonical($normalized)],function()use($p,$s,$id,$normalized){$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$current=$this->campaigns->lockCampaignRecord($s,$id)??throw new CommunicationException('resource_not_found');$this->guard($current,$normalized->expectedRevision,['draft']);$template=$this->campaigns->publishedTemplate($s,$normalized->templateId)??throw new CommunicationException('campaign_template_invalid');if($template->channel!==$normalized->channel)throw new CommunicationException('campaign_channel_invalid');$updated=$this->campaigns->updateCampaign($s,$current,$normalized,$this->actor($p),$this->clock->now());$this->audit($p,$s,$current,$updated,AuditAction::CAMPAIGN_UPDATED);return$this->result($updated);});}
 public function audiencePreview(PrincipalContext$p,EventScope$s,int$id):CampaignAudiencePreview{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$campaign=$this->campaigns->findCampaign($s,$id)??throw new CommunicationException('resource_not_found');if(!in_array($campaign->status,['draft','scheduled'],true))throw new CommunicationException('campaign_transition_invalid');$recipients=$this->campaigns->previewRecipients($s,$campaign);$identities=array_map(static fn(CampaignRecipient$r):string=>$r->identity(),$recipients);sort($identities);return new CampaignAudiencePreview($id,count($identities),hash('sha256',implode("\n",$identities)));}
 public function schedule(PrincipalContext$p,EventScope$s,int$id,int$revision,DateTimeImmutable$at,string$key):IdempotencyOutcome{if($at<=$this->clock->now())throw new CommunicationException('campaign_schedule_invalid');return$this->idempotency->execute($p,$s,'campaign.schedule',$key,['campaign_id'=>$id,'expected_revision'=>$revision,'scheduled_at'=>$at->format(DATE_ATOM)],function()use($p,$s,$id,$revision,$at){$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$current=$this->campaigns->lockCampaignRecord($s,$id)??throw new CommunicationException('resource_not_found');$this->guard($current,$revision,['draft']);$scheduled=$this->campaigns->scheduleCampaign($s,$current,$at,$this->actor($p),$this->clock->now());$this->audit($p,$s,$current,$scheduled,AuditAction::CAMPAIGN_SCHEDULED);return$this->result($scheduled);});}
 public function cancel(PrincipalContext$p,EventScope$s,int$id,int$revision,string$key):IdempotencyOutcome{return$this->idempotency->execute($p,$s,'campaign.cancel',$key,['campaign_id'=>$id,'expected_revision'=>$revision],function()use($p,$s,$id,$revision){$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$current=$this->campaigns->lockCampaignRecord($s,$id)??throw new CommunicationException('resource_not_found');$this->guard($current,$revision,['draft','scheduled']);$cancelled=$this->campaigns->cancelCampaign($s,$current,$this->actor($p),$this->clock->now());$this->audit($p,$s,$current,$cancelled,AuditAction::CAMPAIGN_CANCELLED);return$this->result($cancelled);});}
 private function guard(CampaignRecord$c,int$r,array$statuses):void{if($r<1||$c->revision!==$r)throw new CommunicationException('resource_modified');if(!in_array($c->status,$statuses,true))throw new CommunicationException('campaign_transition_invalid');}
 private function audience(array$a,AudienceMode$m):array{$filter=$a['filter']??'active_invitations';$ids=$a['invitation_ids']??[];if(array_diff(array_keys($a),['filter','invitation_ids'])!==[]||!in_array($filter,['active_invitations','confirmed_attendees'],true)||!is_array($ids)||!array_is_list($ids))throw new CommunicationException('campaign_audience_invalid');$ids=array_values(array_unique($ids));sort($ids,SORT_NUMERIC);foreach($ids as$id)if(!is_int($id)||$id<1)throw new CommunicationException('campaign_audience_invalid');if($m===AudienceMode::SNAPSHOT&&$ids===[])throw new CommunicationException('campaign_snapshot_audience_required');return['mode'=>$m->value,'filter'=>$filter,'invitation_ids'=>$ids];}
 private function canonical(CampaignReplacement$r):array{return['template_id'=>$r->templateId,'name'=>$r->name,'channel'=>$r->channel->value,'purpose'=>$r->purpose->value,'audience_mode'=>$r->audienceMode->value,'audience'=>$r->audience,'expected_revision'=>$r->expectedRevision];}
 private function actor(PrincipalContext$p):int{if($p->type!==PrincipalType::WORDPRESS_USER||$p->userId===null)throw new CommunicationException('campaign_actor_invalid');return$p->userId;}
 private function result(CampaignRecord$c):IdempotentOperationResult{return new IdempotentOperationResult(new IdempotencyResultReference('campaign',$c->campaignId,200),$c);}
 private function audit(PrincipalContext$p,EventScope$s,CampaignRecord$b,CampaignRecord$a,AuditAction$action):void{$this->audit->recordRequired(new AuditEvent($p,$s,$action,AuditEntityType::CAMPAIGN,$a->campaignId,before:['status'=>$b->status,'revision'=>$b->revision],after:['status'=>$a->status,'revision'=>$a->revision]));}
}
