<?php
namespace EventFlow\Application\Communication;
use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext};use EventFlow\Application\Clock\Clock;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};use EventFlow\Application\Job\{JobRepository,JobRequest};use EventFlow\Application\Persistence\EventScope;use EventFlow\Application\Provider\ProviderDispatchGate;
final readonly class MessageAccessService implements MessageAccess
{
    private const STATUSES=['draft','queued','retry_pending','processing','provider_accepted','delivered','failed','uncertain','bounced','cancelled'];
    private const RETRYABLE=['failed','uncertain','bounced'];
    public function __construct(private MessageAccessRepository $messages,private JobRepository $jobs,private AuthorizationService $authorization,private IdempotencyService $idempotency,private AuditService $audit,private Clock $clock,private ?ProviderDispatchGate $dispatchGate=null){}
    public function list(PrincipalContext$p,EventScope$s,int$limit=50,?int$afterMessageId=null,?int$campaignId=null,?string$status=null):MessagePage{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);if($limit<1||$limit>100||($afterMessageId!==null&&$afterMessageId<1)||($campaignId!==null&&$campaignId<1)||($status!==null&&!in_array($status,self::STATUSES,true)))throw new CommunicationException('message_query_invalid');return$this->messages->listMessages($s,$limit,$afterMessageId,$campaignId,$status);}
    public function read(PrincipalContext$p,EventScope$s,int$id):MessageRecord{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);return$this->messages->findMessage($s,$id)??throw new CommunicationException('resource_not_found');}
    public function sendTest(PrincipalContext$p,EventScope$s,CommunicationChannel$channel,string$recipientName,string$recipientAddress,?string$subject,string$content,?string$plainText,string$key):IdempotencyOutcome
    {
        $recipientName=trim($recipientName);$recipientAddress=trim($recipientAddress);$subject=$subject===null?null:trim($subject);
        $emailValid=$channel===CommunicationChannel::EMAIL&&filter_var($recipientAddress,FILTER_VALIDATE_EMAIL)!==false;
        $smsValid=$channel===CommunicationChannel::SMS&&preg_match('/^\+[1-9][0-9]{7,14}$/',$recipientAddress)===1;
        if($recipientName===''||strlen($recipientName)>190||strlen($recipientAddress)>190||(!$emailValid&&!$smsValid)||trim($content)===''||strlen($content)>500000||($channel===CommunicationChannel::SMS&&strlen($content)>1600)||($plainText!==null&&strlen($plainText)>500000)||($channel===CommunicationChannel::EMAIL&&($subject===null||$subject===''||strlen($subject)>500))||($channel===CommunicationChannel::SMS&&$subject!==null))throw new CommunicationException('message_test_invalid');
        $provider=$channel===CommunicationChannel::EMAIL?'brevo':'twilio';
        return$this->idempotency->execute($p,$s,'message.send_test',$key,['channel'=>$channel->value,'recipient_name'=>$recipientName,'recipient_address'=>$recipientAddress,'subject'=>$subject,'content'=>$content,'plain_text'=>$plainText],function()use($p,$s,$channel,$recipientName,$recipientAddress,$subject,$content,$plainText,$provider,$key){
            $this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$this->dispatchGate?->assertEnabled($provider);$now=$this->clock->now();$logical=hash('sha256','test:'.$s->eventId.':'.$key);$message=$this->messages->createTestMessage($s,$channel,$recipientName,$recipientAddress,$subject,$content,$plainText,$logical,$now);$job=$this->jobs->enqueue(JobRequest::create($s,'message.delivery.test',1,['message_id'=>$message->messageId,'provider'=>$provider],[Capability::QUEUE_CAMPAIGN],$now,40,5,'message:'.$message->messageId.':test'),$now);$this->audit->recordRequired(new AuditEvent($p,$s,AuditAction::MESSAGE_TEST_QUEUED,AuditEntityType::MESSAGE,$message->messageId,after:['channel'=>$channel->value,'job_id'=>$job->jobId]));return new IdempotentOperationResult(new IdempotencyResultReference('message',$message->messageId,202),new MessageTestResult($message,$job->jobId));
        });
    }
    public function retry(PrincipalContext$p,EventScope$s,int$id,int$revision,string$key):IdempotencyOutcome{return$this->idempotency->execute($p,$s,'message.retry',$key,['message_id'=>$id,'expected_revision'=>$revision],function()use($p,$s,$id,$revision){$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$current=$this->messages->lockMessage($s,$id)??throw new CommunicationException('resource_not_found');if($revision<1||$current->revision!==$revision)throw new CommunicationException('resource_modified');if(!in_array($current->status,self::RETRYABLE,true))throw new CommunicationException('message_not_retryable');$provider=$current->channel===CommunicationChannel::EMAIL?'brevo':'twilio';$this->dispatchGate?->assertEnabled($provider);$now=$this->clock->now();$retried=$this->messages->markRetryPending($s,$current,$now);$job=$this->jobs->enqueue(JobRequest::create($s,'message.delivery.retry',1,['message_id'=>$id,'provider'=>$provider],[Capability::QUEUE_CAMPAIGN],$now,40,5,'message:'.$id.':retry:'.$retried->revision),$now);$this->audit->recordRequired(new AuditEvent($p,$s,AuditAction::MESSAGE_RETRY_REQUESTED,AuditEntityType::MESSAGE,$id,before:['status'=>$current->status,'revision'=>$current->revision],after:['status'=>$retried->status,'revision'=>$retried->revision,'job_id'=>$job->jobId]));return new IdempotentOperationResult(new IdempotencyResultReference('message',$id,202),new MessageRetryResult($retried,$job->jobId));});}
}
