<?php
namespace EventFlow\Application\Communication;
use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext};use EventFlow\Application\Clock\Clock;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};use EventFlow\Application\Job\{JobRepository,JobRequest};use EventFlow\Application\Persistence\EventScope;
final readonly class MessageAccessService implements MessageAccess
{
    private const STATUSES=['draft','queued','retry_pending','processing','provider_accepted','delivered','failed','uncertain','bounced','cancelled'];
    private const RETRYABLE=['failed','uncertain','bounced'];
    public function __construct(private MessageAccessRepository $messages,private JobRepository $jobs,private AuthorizationService $authorization,private IdempotencyService $idempotency,private AuditService $audit,private Clock $clock){}
    public function list(PrincipalContext$p,EventScope$s,int$limit=50,?int$afterMessageId=null,?int$campaignId=null,?string$status=null):MessagePage{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);if($limit<1||$limit>100||($afterMessageId!==null&&$afterMessageId<1)||($campaignId!==null&&$campaignId<1)||($status!==null&&!in_array($status,self::STATUSES,true)))throw new CommunicationException('message_query_invalid');return$this->messages->listMessages($s,$limit,$afterMessageId,$campaignId,$status);}
    public function read(PrincipalContext$p,EventScope$s,int$id):MessageRecord{$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);return$this->messages->findMessage($s,$id)??throw new CommunicationException('resource_not_found');}
    public function retry(PrincipalContext$p,EventScope$s,int$id,int$revision,string$key):IdempotencyOutcome{return$this->idempotency->execute($p,$s,'message.retry',$key,['message_id'=>$id,'expected_revision'=>$revision],function()use($p,$s,$id,$revision){$this->authorization->requireEventCapability($p,$s,Capability::QUEUE_CAMPAIGN);$current=$this->messages->lockMessage($s,$id)??throw new CommunicationException('resource_not_found');if($revision<1||$current->revision!==$revision)throw new CommunicationException('resource_modified');if(!in_array($current->status,self::RETRYABLE,true))throw new CommunicationException('message_not_retryable');$now=$this->clock->now();$retried=$this->messages->markRetryPending($s,$current,$now);$job=$this->jobs->enqueue(JobRequest::create($s,'message.delivery.retry',1,['message_id'=>$id],[Capability::QUEUE_CAMPAIGN],$now,40,5,'message:'.$id.':retry:'.$retried->revision),$now);$this->audit->recordRequired(new AuditEvent($p,$s,AuditAction::MESSAGE_RETRY_REQUESTED,AuditEntityType::MESSAGE,$id,before:['status'=>$current->status,'revision'=>$current->revision],after:['status'=>$retried->status,'revision'=>$retried->revision,'job_id'=>$job->jobId]));return new IdempotentOperationResult(new IdempotencyResultReference('message',$id,202),new MessageRetryResult($retried,$job->jobId));});}
}
