<?php
namespace EventFlow\Tests\Unit\Presentation\Api;
use DateTimeImmutable;use EventFlow\Application\Authorization\PrincipalContext;use EventFlow\Application\Communication\{CommunicationChannel,MessageAccess,MessagePage,MessageRecord,MessageRetryResult};use EventFlow\Application\Error\RequestIdFactory;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference};use EventFlow\Application\Persistence\EventScope;use EventFlow\Application\Security\SecureRandom;use EventFlow\Presentation\Api\{AuthenticatedPrincipalResolver,AuthenticatedRequestContextFactory,MessageAccessController,MessageAccessPresenter,MessageAccessRequestMapper,MessageAccessRouteRegistrar,RequestInputException,RestRequest,RestRouteRegistry};use PHPUnit\Framework\TestCase;
final class MessageAccessControllerTest extends TestCase
{
 public function testRegistrarExposesAuthoritativeMessageSurface():void{$routes=new MessageAccessMemoryRoutes();(new MessageAccessRouteRegistrar($this->controller(new MessageAccessPort())))->register($routes);self::assertSame(['GET eventflow/v1/events/(?P<event_id>\d+)/messages','GET eventflow/v1/events/(?P<event_id>\d+)/messages/(?P<message_id>\d+)','POST eventflow/v1/events/(?P<event_id>\d+)/messages/(?P<message_id>\d+)/retry'],$routes->registered);}
 public function testListMapsFiltersAndOmitsBodiesAndLogicalKey():void{$port=new MessageAccessPort();$response=$this->controller($port)->list(new RestRequest(routeParameters:['event_id'=>'9'],queryParameters:['limit'=>'25','after'=>'60','campaign_id'=>'21','status'=>'failed']));self::assertSame([25,60,21,'failed'],$port->page);self::assertSame(62,$response->body()['meta']['next_after']);$data=$response->body()['data'][0];self::assertSame('a@example.test',$data['recipient_address']);self::assertArrayNotHasKey('content',$data);self::assertArrayNotHasKey('plain_text',$data);self::assertArrayNotHasKey('logical_key',$data);self::assertSame('no-store, max-age=0',$response->headers()['Cache-Control']);}
 public function testDetailAndRetryExposeRevisionAndDurableJob():void{$port=new MessageAccessPort();$controller=$this->controller($port);$read=$controller->read(new RestRequest(routeParameters:['event_id'=>'9','message_id'=>'61']));self::assertSame('Rendered secret',$read->body()['data']['content']);self::assertSame('"3"',$read->headers()['ETag']);$retry=$controller->retry(new RestRequest(['If-Match'=>'"3"','Idempotency-Key'=>'message-retry-001'],[],['event_id'=>'9','message_id'=>'61']));self::assertSame([61,3,'message-retry-001'],$port->retryInput);self::assertSame(91,$retry->body()['data']['retry_job_id']);self::assertSame('retry_pending',$retry->body()['data']['status']);self::assertSame('"4"',$retry->headers()['ETag']);self::assertSame(202,$retry->status());}
 public function testInvalidQueryRouteBodyAndPreconditionsFailBeforeRetry():void{foreach([fn()=> $this->controller(new MessageAccessPort())->list(new RestRequest(routeParameters:['event_id'=>'9'],queryParameters:['limit'=>'0'])),fn()=> $this->controller(new MessageAccessPort())->list(new RestRequest(routeParameters:['event_id'=>'9'],queryParameters:['campaign_id'=>'2.1'])),fn()=> $this->controller(new MessageAccessPort())->read(new RestRequest(routeParameters:['event_id'=>'9','message_id'=>'../61'])),fn()=> $this->controller(new MessageAccessPort())->retry(new RestRequest(['If-Match'=>'3','Idempotency-Key'=>'message-retry-002'],['force'=>true],['event_id'=>'9','message_id'=>'61'])),fn()=> $this->controller(new MessageAccessPort())->retry(new RestRequest(['Idempotency-Key'=>'message-retry-003'],[],['event_id'=>'9','message_id'=>'61']))]as$operation){try{$operation();self::fail('Expected controlled failure.');}catch(RequestInputException$e){self::assertContains($e->safeCode,['validation_failed','resource_not_found','precondition_required']);}}}
 private function controller(MessageAccess$port):MessageAccessController{return new MessageAccessController($port,new AuthenticatedRequestContextFactory(new MessageAccessPrincipal(),new RequestIdFactory(new MessageAccessRandom())),new MessageAccessRequestMapper(),new MessageAccessPresenter());}
}
final class MessageAccessMemoryRoutes implements RestRouteRegistry{public array$registered=[];public function registerPublicGet(string$n,string$r,callable$h):void{}public function registerPublicPost(string$n,string$r,callable$h):void{}public function registerPublicPut(string$n,string$r,callable$h):void{}public function registerAuthenticatedGet(string$n,string$r,callable$h):void{$this->registered[]='GET '.$n.$r;}public function registerAuthenticatedPost(string$n,string$r,callable$h):void{$this->registered[]='POST '.$n.$r;}public function registerAuthenticatedPatch(string$n,string$r,callable$h):void{}}
final readonly class MessageAccessPrincipal implements AuthenticatedPrincipalResolver{public function resolve(RestRequest$r):PrincipalContext{return PrincipalContext::wordpressUser(7);}}
final readonly class MessageAccessRandom implements SecureRandom{public function hex(int$b):string{return str_repeat('7',$b*2);}}
final class MessageAccessPort implements MessageAccess
{public array$page=[];public array$retryInput=[];public function list(PrincipalContext$p,EventScope$s,int$l=50,?int$a=null,?int$c=null,?string$status=null):MessagePage{$this->page=[$l,$a,$c,$status];return new MessagePage([$this->record()],62);}public function read(PrincipalContext$p,EventScope$s,int$id):MessageRecord{return$this->record();}public function retry(PrincipalContext$p,EventScope$s,int$id,int$r,string$key):IdempotencyOutcome{$this->retryInput=[$id,$r,$key];$message=$this->record('retry_pending',4);return new IdempotencyOutcome(false,new IdempotencyResultReference('message',$id,202),new MessageRetryResult($message,91));}private function record(string$status='failed',int$revision=3):MessageRecord{return new MessageRecord(61,21,hash('sha256','logical'),'a@example.test','Subject','Rendered secret',CommunicationChannel::EMAIL,$status,$revision,11,12,'Guest','Plain secret','mail','pm-1',2,new DateTimeImmutable('2026-08-19T18:00:00Z'),failedAt:new DateTimeImmutable('2026-08-19T18:05:00Z'),createdAt:new DateTimeImmutable('2026-08-19T17:55:00Z'),updatedAt:new DateTimeImmutable('2026-08-19T18:05:00Z'));}}
