<?php
namespace EventFlow\Tests\Unit\Presentation\Api;
use DateTimeImmutable;
use EventFlow\Application\Authorization\PrincipalContext;
use EventFlow\Application\Error\RequestIdFactory;
use EventFlow\Application\EventConfiguration\{EventConfigurationAttributes,EventConfigurationOperations,EventConfigurationPatch,EventConfigurationRecord};
use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference};
use EventFlow\Application\Persistence\EventScope;
use EventFlow\Application\Security\SecureRandom;
use EventFlow\Application\Venue\{VenueAttributes,VenueOperations,VenuePage,VenuePatch,VenueRecord};
use EventFlow\Presentation\Api\{AuthenticatedPrincipalResolver,AuthenticatedRequestContextFactory,EventConfigurationController,EventConfigurationPresenter,EventConfigurationRequestMapper,EventConfigurationRouteRegistrar,RequestInputException,RestRequest,RestRouteRegistry,VenueController,VenuePresenter,VenueRequestMapper,VenueRouteRegistrar};
use PHPUnit\Framework\TestCase;
final class VenueConfigurationControllerTest extends TestCase
{
    public function testRegistrarsExposeOnlyAcceptedAuthenticatedRoutes():void{$routes=new VCRoutes();(new VenueRouteRegistrar($this->venues(new VCVenuePort())))->register($routes);(new EventConfigurationRouteRegistrar($this->config(new VCConfigPort())))->register($routes);self::assertSame(['GET eventflow/v1/venues','GET eventflow/v1/venues/(?P<venue_id>\d+)','GET eventflow/v1/events/(?P<event_id>\d+)/configuration'],array_keys($routes->gets));self::assertSame(['POST eventflow/v1/venues'],array_keys($routes->posts));self::assertSame(['PATCH eventflow/v1/venues/(?P<venue_id>\d+)','PATCH eventflow/v1/events/(?P<event_id>\d+)/configuration'],array_keys($routes->patches));}
    public function testVenueCollectionCreateDetailAndUpdateMapExplicitly():void{$port=new VCVenuePort();$controller=$this->venues($port);$list=$controller->list(new RestRequest(queryParameters:['limit'=>'20','after'=>'5']));$create=$controller->create(new RestRequest(['Idempotency-Key'=>'venue-create-001'],['name'=>'Hall','country_code'=>'CA','default_capacity'=>200]));$read=$controller->read(new RestRequest(routeParameters:['venue_id'=>'81']));$update=$controller->update(new RestRequest(['If-Match'=>'"1"','Idempotency-Key'=>'venue-update-001'],['city'=>'Calgary'],['venue_id'=>'81']));self::assertSame([20,5],$port->venuePage);self::assertSame('Hall',$create->body()['data']['name']);self::assertSame('"1"',$read->headers()['ETag']);self::assertSame('Calgary',$port->venuePatch?->changes['city']);self::assertSame('"2"',$update->headers()['ETag']);self::assertSame(81,$list->body()['data'][0]['id']);}
    public function testConfigurationReadAndUpdateMapDatesBooleansAndEtag():void{$port=new VCConfigPort();$controller=$this->config($port);$read=$controller->read(new RestRequest(routeParameters:['event_id'=>'51']));$update=$controller->update(new RestRequest(['If-Match'=>'"3"','Idempotency-Key'=>'config-update-001'],['allow_guest_edits'=>true,'confirmation_closes_at'=>'2026-09-02T00:00:00Z'],['event_id'=>'51']));self::assertSame('"3"',$read->headers()['ETag']);self::assertTrue($port->patch?->changes['allow_guest_edits']);self::assertInstanceOf(DateTimeImmutable::class,$port->patch?->changes['confirmation_closes_at']);self::assertSame('"4"',$update->headers()['ETag']);}
    public function testMalformedInputsAndMissingPreconditionsFailBeforePorts():void{foreach([fn($p)=>$this->venues($p)->list(new RestRequest(queryParameters:['limit'=>'101'])),fn($p)=>$this->venues($p)->create(new RestRequest(['Idempotency-Key'=>'venue-create-002'],['name'=>'Hall','admin'=>true])),fn($p)=>$this->venues($p)->update(new RestRequest(['If-Match'=>'"1"'],['city'=>'X'],['venue_id'=>'81']))] as $operation){$port=new VCVenuePort();try{$operation($port);self::fail('Expected rejection.');}catch(RequestInputException $failure){self::assertContains($failure->safeCode,['validation_failed','precondition_required']);}self::assertSame([],$port->calls);}$port=new VCConfigPort();try{$this->config($port)->update(new RestRequest(['If-Match'=>'"3"','Idempotency-Key'=>'config-update-002'],['confirmation_opens_at'=>'tomorrow'],['event_id'=>'51']));self::fail('Expected rejection.');}catch(RequestInputException $failure){self::assertSame('validation_failed',$failure->safeCode);}self::assertSame([],$port->calls);}
    private function contexts():AuthenticatedRequestContextFactory{return new AuthenticatedRequestContextFactory(new VCResolver(),new RequestIdFactory(new VCRandom()));}
    private function venues(VCVenuePort $port):VenueController{return new VenueController($port,$this->contexts(),new VenueRequestMapper(),new VenuePresenter());}
    private function config(VCConfigPort $port):EventConfigurationController{return new EventConfigurationController($port,$this->contexts(),new EventConfigurationRequestMapper(),new EventConfigurationPresenter());}
}
final class VCVenuePort implements VenueOperations
{
    public array $calls=[];public array $venuePage=[];public ?VenuePatch $venuePatch=null;
    public function list(PrincipalContext $p,int $limit=50,?int $afterVenueId=null):VenuePage{$this->calls[]='venue.list';$this->venuePage=[$limit,$afterVenueId];return new VenuePage([$this->venue(1)],null);}
    public function read(PrincipalContext $p,int $venueId):VenueRecord{$this->calls[]='venue.read';return $this->venue(1);}
    public function create(PrincipalContext $p,VenueAttributes $a,string $key):IdempotencyOutcome{$this->calls[]='venue.create';return new IdempotencyOutcome(false,new IdempotencyResultReference('venue',81,201),new VenueRecord(81,$a,1));}
    public function update(PrincipalContext $p,int $venueId,VenuePatch $patch,string $key):IdempotencyOutcome{$this->calls[]='venue.update';$this->venuePatch=$patch;return new IdempotencyOutcome(false,new IdempotencyResultReference('venue',81,200),new VenueRecord(81,$patch->applyTo($this->venue(1)),2));}
    private function venue(int $revision):VenueRecord{return new VenueRecord(81,new VenueAttributes(['name'=>'Hall']),$revision);}
}
final class VCConfigPort implements EventConfigurationOperations{public array $calls=[];public ?EventConfigurationPatch $patch=null;public function read(PrincipalContext $p,EventScope $scope):EventConfigurationRecord{$this->calls[]='configuration.read';return $this->record(3);}public function update(PrincipalContext $p,EventScope $scope,EventConfigurationPatch $patch,string $key):IdempotencyOutcome{$this->calls[]='configuration.update';$this->patch=$patch;return new IdempotencyOutcome(false,new IdempotencyResultReference('event_configuration',51,200),new EventConfigurationRecord($scope,$patch->applyTo($this->record(3)),4));}private function record(int $revision):EventConfigurationRecord{return new EventConfigurationRecord(new EventScope(51),new EventConfigurationAttributes(),$revision);}}
final readonly class VCResolver implements AuthenticatedPrincipalResolver{public function resolve(RestRequest $request):PrincipalContext{return PrincipalContext::wordpressUser(7);}}
final readonly class VCRandom implements SecureRandom{public function hex(int $bytes):string{return str_repeat('d',$bytes*2);}}
final class VCRoutes implements RestRouteRegistry{public array $gets=[];public array $posts=[];public array $patches=[];public function registerPublicGet(string $n,string $r,callable $h):void{}public function registerPublicPost(string $n,string $r,callable $h):void{}public function registerPublicPut(string $n,string $r,callable $h):void{}public function registerAuthenticatedGet(string $n,string $r,callable $h):void{$this->gets['GET '.$n.$r]=$h;}public function registerAuthenticatedPost(string $n,string $r,callable $h):void{$this->posts['POST '.$n.$r]=$h;}public function registerAuthenticatedPatch(string $n,string $r,callable $h):void{$this->patches['PATCH '.$n.$r]=$h;}}
