<?php
namespace EventFlow\Infrastructure\Persistence\WordPress;
use DateTimeImmutable;use DateTimeZone;use EventFlow\Application\Export\{ExportException,ExportFormat,ExportRecord,ExportRepository,ExportType,PublishedExportArtifact};use EventFlow\Application\Persistence\EventScope;use EventFlow\Infrastructure\Persistence\{PersistenceException,TableName};
final class WpdbExportRepository extends AbstractWpdbRepository implements ExportRepository
{
 public function create(EventScope $s,ExportType $type,ExportFormat $format,string $purpose,DateTimeImmutable $cutoff,DateTimeImmutable $expires,?int $actor,DateTimeImmutable $now):ExportRecord{$t=$this->table(TableName::EXPORTS);$ts=$this->ts($now);$sql="INSERT INTO {$t} (event_id,requested_by_user_id,export_type,export_format,contains_pii,purpose,temporal_mode,cutoff_at,export_status,expires_at,created_at,updated_at) VALUES (%d,".($actor===null?'NULL':'%d').",%s,%s,%d,%s,'requested_at_snapshot',%s,'pending',%s,%s,%s)";$p=[$s->eventId];if($actor!==null)$p[]=$actor;array_push($p,$type->value,$format->value,$type->containsPii()?1:0,$purpose,$this->ts($cutoff),$this->ts($expires),$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('export_create_failed');return new ExportRecord($this->database->lastInsertId(),$s,$type,$format,$type->containsPii(),$purpose,$cutoff,'pending',$expires);}
 public function lock(EventScope $s,int $id):?ExportRecord{$t=$this->table(TableName::EXPORTS);$r=$this->database->fetchRow("SELECT * FROM {$t} WHERE event_id=%d AND export_id=%d LIMIT 1 FOR UPDATE",[$s->eventId,$id]);return $r===null?null:$this->hydrate($r,$s);}
 public function beginGeneration(EventScope $s,int $id,int $max,DateTimeImmutable $now):ExportRecord{$config=$this->table(TableName::EVENT_CONFIGURATIONS);$this->database->fetchValue("SELECT event_id FROM {$config} WHERE event_id=%d LIMIT 1 FOR UPDATE",[$s->eventId]);$t=$this->table(TableName::EXPORTS);$active=(int)$this->database->fetchValue("SELECT COUNT(*) FROM {$t} WHERE event_id=%d AND export_status='generating'",[$s->eventId]);if($active>=$max)throw new ExportException('export_concurrency_limit');$export=$this->lock($s,$id)??throw new ExportException('resource_not_found');if($export->status!=='pending'||$export->expiresAt<=$now)throw new ExportException('export_not_ready');if($this->database->execute("UPDATE {$t} SET export_status='generating',updated_at=%s WHERE event_id=%d AND export_id=%d AND export_status='pending'",[$this->ts($now),$s->eventId,$id])!==1)throw new ExportException('resource_modified');return new ExportRecord($export->exportId,$s,$export->type,$export->format,$export->containsPii,$export->purpose,$export->cutoffAt,'generating',$export->expiresAt);}
 public function markReady(ExportRecord $e,PublishedExportArtifact $a,DateTimeImmutable $now):ExportRecord{$t=$this->table(TableName::EXPORTS);if($this->database->execute("UPDATE {$t} SET export_status='ready',artifact_locator=%s,artifact_sha256=%s,artifact_mime_type=%s,artifact_size_bytes=%d,updated_at=%s WHERE event_id=%d AND export_id=%d AND export_status='generating'",[$a->locator,$a->sha256,$a->mimeType,$a->sizeBytes,$this->ts($now),$e->eventScope->eventId,$e->exportId])!==1)throw new ExportException('resource_modified');return new ExportRecord($e->exportId,$e->eventScope,$e->type,$e->format,$e->containsPii,$e->purpose,$e->cutoffAt,'ready',$e->expiresAt,$a->locator,$a->sha256,$a->mimeType,$a->sizeBytes);}
 public function markFailed(ExportRecord $e,string $code,DateTimeImmutable $now):void{$t=$this->table(TableName::EXPORTS);$this->database->execute("UPDATE {$t} SET export_status='failed',failure_code=%s,updated_at=%s WHERE event_id=%d AND export_id=%d AND export_status='generating'",[$code,$this->ts($now),$e->eventScope->eventId,$e->exportId]);}
 public function recordDownload(ExportRecord $e,DateTimeImmutable $now):void{$t=$this->table(TableName::EXPORTS);if($this->database->execute("UPDATE {$t} SET download_count=download_count+1,updated_at=%s WHERE event_id=%d AND export_id=%d AND export_status='ready' AND expires_at>%s",[$this->ts($now),$e->eventScope->eventId,$e->exportId,$this->ts($now)])!==1)throw new ExportException('export_not_downloadable');}
 private function hydrate(array $r,EventScope $s):ExportRecord{return new ExportRecord((int)$r['export_id'],$s,ExportType::from($r['export_type']),ExportFormat::from($r['export_format']),(bool)$r['contains_pii'],(string)$r['purpose'],$this->date($r['cutoff_at']),(string)$r['export_status'],$this->date($r['expires_at']),$r['artifact_locator'],$r['artifact_sha256'],$r['artifact_mime_type'],$r['artifact_size_bytes']===null?null:(int)$r['artifact_size_bytes']);}
 private function date(string $v):DateTimeImmutable{return new DateTimeImmutable($v,new DateTimeZone('UTC'));}private function ts(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}
}
