<?php

namespace EventFlow\Infrastructure\Persistence\WordPress;

use DateTimeImmutable;
use DateTimeZone;
use EventFlow\Application\Communication\AudienceMode;
use EventFlow\Application\Communication\CampaignPurpose;
use EventFlow\Application\Communication\CampaignRecord;
use EventFlow\Application\Communication\CampaignAccessRepository;
use EventFlow\Application\Communication\CampaignPage;
use EventFlow\Application\Communication\CampaignReplacement;
use EventFlow\Application\Communication\CampaignRecipient;
use EventFlow\Application\Communication\CommunicationChannel;
use EventFlow\Application\Communication\CommunicationException;
use EventFlow\Application\Communication\CommunicationRepository;
use EventFlow\Application\Communication\MessageRecord;
use EventFlow\Application\Communication\MessageAccessRepository;
use EventFlow\Application\Communication\MessagePage;
use EventFlow\Application\Communication\TemplateRecord;
use EventFlow\Application\Communication\TemplateAccessRepository;
use EventFlow\Application\Communication\TemplatePage;
use EventFlow\Application\Communication\TemplateReplacement;
use EventFlow\Application\Persistence\EventScope;
use EventFlow\Infrastructure\Persistence\PersistenceException;
use EventFlow\Infrastructure\Persistence\TableName;

final class WpdbCommunicationRepository extends AbstractWpdbRepository implements CommunicationRepository, TemplateAccessRepository, CampaignAccessRepository, MessageAccessRepository
{
    public function createDraft(EventScope $scope, string $key, string $name, CommunicationChannel $channel, string $type, ?string $subject, string $body, ?string $plainText, array $allowedFields, ?int $actor, DateTimeImmutable $now): TemplateRecord
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$latest=$this->database->fetchRow("SELECT version_number FROM {$table} WHERE event_id=%d AND template_key=%s AND channel=%s AND deleted_at IS NULL ORDER BY version_number DESC LIMIT 1 FOR UPDATE",[$scope->eventId,$key,$channel->value]);$version=((int)($latest['version_number']??0))+1;$ts=$this->ts($now);
        $sql="INSERT INTO {$table} (event_id,template_key,template_name,channel,template_type,template_status,version_number,subject_template,body_template,plain_text_template,allowed_merge_fields,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%s,%s,%s,%s,'draft',%d,".($subject===null?'NULL':'%s').",%s,".($plainText===null?'NULL':'%s').",%s,".($actor===null?'NULL,NULL':'%d,%d').",%s,%s)";$p=[$scope->eventId,$key,$name,$channel->value,$type,$version];if($subject!==null)$p[]=$subject;$p[]=$body;if($plainText!==null)$p[]=$plainText;$p[]=json_encode($allowedFields,JSON_THROW_ON_ERROR);if($actor!==null){$p[]=$actor;$p[]=$actor;}array_push($p,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('template_create_failed');return new TemplateRecord($this->database->lastInsertId(),$key,$name,$channel,$version,'draft',$subject,$body,$plainText,$allowedFields,$type,1,$now,$now);
    }

    public function listTemplates(EventScope $scope,int $limit,?int $afterTemplateId):TemplatePage
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$after=$afterTemplateId===null?'':' AND template_id>%d';$parameters=[$scope->eventId];if($afterTemplateId!==null)$parameters[]=$afterTemplateId;$parameters[]=$limit+1;
        $rows=$this->database->fetchAll('SELECT '.$this->accessColumns()." FROM {$table} WHERE event_id=%d AND deleted_at IS NULL{$after} ORDER BY template_id ASC LIMIT %d",$parameters);$more=count($rows)>$limit;if($more)array_pop($rows);$records=array_map(fn(array $row):TemplateRecord=>$this->accessTemplate($row),$rows);
        return new TemplatePage($records,$more&&$records!==[]?$records[array_key_last($records)]->templateId:null);
    }

    public function findTemplate(EventScope $scope,int $templateId):?TemplateRecord{return $this->templateRecord($scope,$templateId,false);}
    public function lockTemplate(EventScope $scope,int $templateId):?TemplateRecord{return $this->templateRecord($scope,$templateId,true);}

    public function updateTemplate(EventScope $scope,TemplateRecord $current,TemplateReplacement $replacement,int $actorUserId,DateTimeImmutable $now):TemplateRecord
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$parameters=[$replacement->name,$replacement->type];$subject=$this->nullable($replacement->subject,'%s',$parameters);$parameters[]=$replacement->body;$plain=$this->nullable($replacement->plainText,'%s',$parameters);$parameters[]=json_encode($replacement->allowedFields,JSON_THROW_ON_ERROR);array_push($parameters,$actorUserId,$this->ts($now),$scope->eventId,$current->templateId,$current->revision);
        $affected=$this->database->execute("UPDATE {$table} SET template_name=%s,template_type=%s,subject_template={$subject},body_template=%s,plain_text_template={$plain},allowed_merge_fields=%s,template_revision=template_revision+1,updated_by_user_id=%d,updated_at=%s WHERE event_id=%d AND template_id=%d AND template_revision=%d AND template_status='draft' AND deleted_at IS NULL",$parameters);
        if($affected!==1)throw new CommunicationException('resource_modified');
        return new TemplateRecord($current->templateId,$current->templateKey,$replacement->name,$current->channel,$current->version,'draft',$replacement->subject,$replacement->body,$replacement->plainText,$replacement->allowedFields,$replacement->type,$current->revision+1,$current->createdAt,$now,$current->publishedAt,$current->archivedAt);
    }

    public function createTemplateVersion(EventScope $scope,TemplateRecord $source,int $actorUserId,DateTimeImmutable $now):TemplateRecord
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$latest=(int)($this->database->fetchValue("SELECT version_number FROM {$table} WHERE event_id=%d AND template_key=%s AND channel=%s AND deleted_at IS NULL ORDER BY version_number DESC LIMIT 1 FOR UPDATE",[$scope->eventId,$source->templateKey,$source->channel->value])??0);$version=$latest+1;$parameters=[$scope->eventId,$source->templateKey,$source->name,$source->channel->value,$source->type,$version];$subject=$this->nullable($source->subject,'%s',$parameters);$parameters[]=$source->body;$plain=$this->nullable($source->plainText,'%s',$parameters);$parameters[]=json_encode($source->allowedFields,JSON_THROW_ON_ERROR);array_push($parameters,$actorUserId,$actorUserId,$this->ts($now),$this->ts($now));
        $sql="INSERT INTO {$table} (event_id,template_key,template_name,channel,template_type,template_status,version_number,template_revision,subject_template,body_template,plain_text_template,allowed_merge_fields,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%s,%s,%s,%s,'draft',%d,1,{$subject},%s,{$plain},%s,%d,%d,%s,%s)";
        if($this->database->execute($sql,$parameters)!==1)throw new PersistenceException('template_create_failed');
        return new TemplateRecord($this->database->lastInsertId(),$source->templateKey,$source->name,$source->channel,$version,'draft',$source->subject,$source->body,$source->plainText,$source->allowedFields,$source->type,1,$now,$now);
    }

    public function archiveTemplate(EventScope $scope,TemplateRecord $current,int $actorUserId,DateTimeImmutable $now):TemplateRecord
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$timestamp=$this->ts($now);$affected=$this->database->execute("UPDATE {$table} SET template_status='archived',archived_at=%s,template_revision=template_revision+1,updated_by_user_id=%d,updated_at=%s WHERE event_id=%d AND template_id=%d AND template_revision=%d AND template_status<>'archived' AND deleted_at IS NULL",[$timestamp,$actorUserId,$timestamp,$scope->eventId,$current->templateId,$current->revision]);if($affected!==1)throw new CommunicationException('resource_modified');
        return new TemplateRecord($current->templateId,$current->templateKey,$current->name,$current->channel,$current->version,'archived',$current->subject,$current->body,$current->plainText,$current->allowedFields,$current->type,$current->revision+1,$current->createdAt,$now,$current->publishedAt,$now);
    }

    public function templateHasMutableCampaigns(EventScope $scope,int $templateId):bool{$table=$this->table(TableName::CAMPAIGNS);return (int)$this->database->fetchValue("SELECT COUNT(*) FROM {$table} WHERE event_id=%d AND template_id=%d AND campaign_status IN ('draft','scheduled') AND deleted_at IS NULL",[$scope->eventId,$templateId])>0;}
    public function publish(EventScope $scope,int $templateId,?int $actor,DateTimeImmutable $now):TemplateRecord{$t=$this->table(TableName::COMMUNICATION_TEMPLATES);$r=$this->database->fetchRow("SELECT template_id,template_key,template_name,channel,template_type,version_number,template_revision,template_status,subject_template,body_template,plain_text_template,allowed_merge_fields FROM {$t} WHERE event_id=%d AND template_id=%d AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$scope->eventId,$templateId]);if($r===null)throw new CommunicationException('resource_not_found');if($r['template_status']!=='draft')throw new CommunicationException('template_immutable');$ts=$this->ts($now);$sql="UPDATE {$t} SET template_status='published',published_at=%s,template_revision=template_revision+1,updated_by_user_id=".($actor===null?'NULL':'%d').",updated_at=%s WHERE event_id=%d AND template_id=%d AND template_revision=%d AND template_status='draft'";$p=[$ts];if($actor!==null)$p[]=$actor;array_push($p,$ts,$scope->eventId,$templateId,(int)$r['template_revision']);if($this->database->execute($sql,$p)!==1)throw new CommunicationException('resource_modified');$r['template_status']='published';$template=$this->template($r);return new TemplateRecord($template->templateId,$template->templateKey,$template->name,$template->channel,$template->version,'published',$template->subject,$template->body,$template->plainText,$template->allowedFields,$template->type,(int)$r['template_revision']+1,publishedAt:$now);}
    public function createCampaign(EventScope $scope,int $templateId,string $name,CommunicationChannel $channel,CampaignPurpose $purpose,AudienceMode $mode,array $audience,?int $actor,DateTimeImmutable $now):CampaignRecord{$this->lockPublishedTemplate($scope,$templateId)??throw new CommunicationException('campaign_template_invalid');if($mode===AudienceMode::SNAPSHOT&&$audience['invitation_ids']===[]){$i=$this->table(TableName::INVITATIONS);$audience['invitation_ids']=array_map('intval',$this->database->fetchAll("SELECT invitation_id FROM {$i} WHERE event_id=%d AND invitation_status='active' AND deleted_at IS NULL ORDER BY invitation_id FOR UPDATE",[$scope->eventId]));}$t=$this->table(TableName::CAMPAIGNS);$ts=$this->ts($now);$json=json_encode($audience,JSON_THROW_ON_ERROR);$sql="INSERT INTO {$t} (event_id,template_id,campaign_name,channel,campaign_type,campaign_status,audience_definition,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%d,%s,%s,%s,'draft',%s,".($actor===null?'NULL,NULL':'%d,%d').",%s,%s)";$p=[$scope->eventId,$templateId,$name,$channel->value,$purpose->value,$json];if($actor!==null){$p[]=$actor;$p[]=$actor;}array_push($p,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('campaign_create_failed');return new CampaignRecord($this->database->lastInsertId(),$templateId,$name,$channel,$purpose,$mode,$audience,'draft');}
    public function listCampaigns(EventScope $scope,int $limit,?int $afterCampaignId):CampaignPage{$t=$this->table(TableName::CAMPAIGNS);$after=$afterCampaignId===null?'':' AND campaign_id>%d';$p=[$scope->eventId];if($afterCampaignId!==null)$p[]=$afterCampaignId;$p[]=$limit+1;$rows=$this->database->fetchAll('SELECT '.$this->campaignColumns()." FROM {$t} WHERE event_id=%d AND deleted_at IS NULL{$after} ORDER BY campaign_id ASC LIMIT %d",$p);$more=count($rows)>$limit;if($more)array_pop($rows);$records=array_map(fn(array$r):CampaignRecord=>$this->campaign($r),$rows);return new CampaignPage($records,$more&&$records!==[]?$records[array_key_last($records)]->campaignId:null);}
    public function findCampaign(EventScope $scope,int $id):?CampaignRecord{return $this->campaignRecord($scope,$id,false);}
    public function lockCampaignRecord(EventScope $scope,int $id):?CampaignRecord{return $this->campaignRecord($scope,$id,true);}
    public function updateCampaign(EventScope $s,CampaignRecord $c,CampaignReplacement $r,int $actor,DateTimeImmutable $now):CampaignRecord{$t=$this->table(TableName::CAMPAIGNS);$affected=$this->database->execute("UPDATE {$t} SET template_id=%d,campaign_name=%s,channel=%s,campaign_type=%s,audience_definition=%s,campaign_revision=campaign_revision+1,updated_by_user_id=%d,updated_at=%s WHERE event_id=%d AND campaign_id=%d AND campaign_revision=%d AND campaign_status='draft' AND deleted_at IS NULL",[$r->templateId,$r->name,$r->channel->value,$r->purpose->value,json_encode($r->audience,JSON_THROW_ON_ERROR),$actor,$this->ts($now),$s->eventId,$c->campaignId,$c->revision]);if($affected!==1)throw new CommunicationException('resource_modified');return new CampaignRecord($c->campaignId,$r->templateId,$r->name,$r->channel,$r->purpose,$r->audienceMode,$r->audience,'draft',$c->revision+1);}
    public function scheduleCampaign(EventScope $s,CampaignRecord $c,DateTimeImmutable $at,int $actor,DateTimeImmutable $now):CampaignRecord{$t=$this->table(TableName::CAMPAIGNS);$affected=$this->database->execute("UPDATE {$t} SET campaign_status='scheduled',scheduled_at=%s,campaign_revision=campaign_revision+1,updated_by_user_id=%d,updated_at=%s WHERE event_id=%d AND campaign_id=%d AND campaign_revision=%d AND campaign_status='draft' AND deleted_at IS NULL",[$this->ts($at),$actor,$this->ts($now),$s->eventId,$c->campaignId,$c->revision]);if($affected!==1)throw new CommunicationException('resource_modified');return new CampaignRecord($c->campaignId,$c->templateId,$c->name,$c->channel,$c->purpose,$c->audienceMode,$c->audienceDefinition,'scheduled',$c->revision+1,$at);}
    public function cancelCampaign(EventScope $s,CampaignRecord $c,int $actor,DateTimeImmutable $now):CampaignRecord{$t=$this->table(TableName::CAMPAIGNS);$affected=$this->database->execute("UPDATE {$t} SET campaign_status='cancelled',cancelled_at=%s,campaign_revision=campaign_revision+1,updated_by_user_id=%d,updated_at=%s WHERE event_id=%d AND campaign_id=%d AND campaign_revision=%d AND campaign_status IN ('draft','scheduled') AND deleted_at IS NULL",[$this->ts($now),$actor,$this->ts($now),$s->eventId,$c->campaignId,$c->revision]);if($affected!==1)throw new CommunicationException('resource_modified');return new CampaignRecord($c->campaignId,$c->templateId,$c->name,$c->channel,$c->purpose,$c->audienceMode,$c->audienceDefinition,'cancelled',$c->revision+1,$c->scheduledAt,$c->startedAt,$c->completedAt,$now,$c->recipientCount);}
    public function publishedTemplate(EventScope $scope,int $templateId):?TemplateRecord{return $this->lockPublishedTemplate($scope,$templateId);}
    public function previewRecipients(EventScope $scope,CampaignRecord $campaign):array{return $this->resolveRecipients($scope,$campaign);}
    public function lockCampaign(EventScope $s,int $id):?CampaignRecord{return $this->campaignRecord($s,$id,true);}
    public function lockPublishedTemplate(EventScope $s,int $id):?TemplateRecord{$t=$this->table(TableName::COMMUNICATION_TEMPLATES);$r=$this->database->fetchRow("SELECT template_id,template_key,template_name,channel,template_type,version_number,template_revision,template_status,subject_template,body_template,plain_text_template,allowed_merge_fields FROM {$t} WHERE event_id=%d AND template_id=%d AND template_status='published' AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$s->eventId,$id]);return $r===null?null:$this->template($r);}
    public function resolveRecipients(EventScope $s,CampaignRecord $c):array{$ids=$c->audienceDefinition['invitation_ids']??[];$where=$ids===[]?'':(' AND i.invitation_id IN ('.implode(',',array_fill(0,count($ids),'%d')).')');$i=$this->table(TableName::INVITATIONS);$a=$this->table(TableName::ATTENDEES);if(($c->audienceDefinition['filter']??'')==='confirmed_attendees'){$rows=$this->database->fetchAll("SELECT i.invitation_id,a.attendee_id,a.display_name,COALESCE(a.email,i.email) address FROM {$a} a JOIN {$i} i ON i.event_id=a.event_id AND i.invitation_id=a.invitation_id WHERE a.event_id=%d AND a.attendance_status='confirmed' AND a.deleted_at IS NULL{$where} ORDER BY a.attendee_id",[$s->eventId,...$ids]);}else{$rows=$this->database->fetchAll("SELECT i.invitation_id,NULL attendee_id,i.primary_name display_name,i.email address FROM {$i} i WHERE i.event_id=%d AND i.invitation_status='active' AND i.email IS NOT NULL AND i.deleted_at IS NULL{$where} ORDER BY i.invitation_id",[$s->eventId,...$ids]);}return array_map(static fn($r)=>new CampaignRecipient((int)$r['invitation_id'],$r['attendee_id']===null?null:(int)$r['attendee_id'],(string)$r['display_name'],(string)$r['address'],['recipient_name'=>(string)$r['display_name'],'guest_link'=>'']),$rows);}
    public function createOrFindMessage(EventScope $s,CampaignRecord $c,CampaignRecipient $r,string $key,?string $subject,string $body,?string $plain,DateTimeImmutable $now):MessageRecord{$t=$this->table(TableName::MESSAGES);$existing=$this->database->fetchRow("SELECT message_id,campaign_id,idempotency_key,recipient_address,subject,rendered_content FROM {$t} WHERE idempotency_key=%s LIMIT 1 FOR UPDATE",[$key]);if($existing!==null)return new MessageRecord((int)$existing['message_id'],(int)$existing['campaign_id'],$key,(string)$existing['recipient_address'],$existing['subject'],(string)$existing['rendered_content']);$ts=$this->ts($now);$sql="INSERT INTO {$t} (event_id,campaign_id,invitation_id,attendee_id,channel,recipient_name,recipient_address,recipient_address_normalized,subject,rendered_content,plain_text_content,delivery_status,idempotency_key,queued_at,created_at,updated_at) VALUES (%d,%d,%d,".($r->attendeeId===null?'NULL':'%d').",%s,%s,%s,%s,".($subject===null?'NULL':'%s').",%s,".($plain===null?'NULL':'%s').",'queued',%s,%s,%s,%s)";$p=[$s->eventId,$c->campaignId,$r->invitationId];if($r->attendeeId!==null)$p[]=$r->attendeeId;array_push($p,$c->channel->value,$r->name,$r->address,strtolower($r->address));if($subject!==null)$p[]=$subject;$p[]=$body;if($plain!==null)$p[]=$plain;array_push($p,$key,$ts,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('message_create_failed');return new MessageRecord($this->database->lastInsertId(),$c->campaignId,$key,$r->address,$subject,$body);}
    public function freezeQueued(EventScope $s,CampaignRecord $c,int $count,DateTimeImmutable $now):void{$t=$this->table(TableName::CAMPAIGNS);$ts=$this->ts($now);if($this->database->execute("UPDATE {$t} SET campaign_status='queued',audience_snapshot_count=%d,queued_count=%d,started_at=%s,campaign_revision=campaign_revision+1,updated_at=%s WHERE event_id=%d AND campaign_id=%d AND campaign_revision=%d AND campaign_status IN ('draft','scheduled')",[$count,$count,$ts,$ts,$s->eventId,$c->campaignId,$c->revision])!==1)throw new CommunicationException('campaign_already_queued');}
    public function listMessages(EventScope $s,int $limit,?int $after,?int $campaignId,?string $status):MessagePage{$t=$this->table(TableName::MESSAGES);$where='';$p=[$s->eventId];if($after!==null){$where.=' AND message_id>%d';$p[]=$after;}if($campaignId!==null){$where.=' AND campaign_id=%d';$p[]=$campaignId;}if($status!==null){$where.=' AND delivery_status=%s';$p[]=$status;}$p[]=$limit+1;$rows=$this->database->fetchAll('SELECT '.$this->messageColumns()." FROM {$t} WHERE event_id=%d{$where} ORDER BY message_id ASC LIMIT %d",$p);$more=count($rows)>$limit;if($more)array_pop($rows);$messages=array_map(fn(array$r):MessageRecord=>$this->message($r),$rows);return new MessagePage($messages,$more&&$messages!==[]?$messages[array_key_last($messages)]->messageId:null);}
    public function findMessage(EventScope $s,int $id):?MessageRecord{return$this->messageRecord($s,$id,false);}
    public function lockMessage(EventScope $s,int $id):?MessageRecord{return$this->messageRecord($s,$id,true);}
    public function markRetryPending(EventScope $s,MessageRecord $current,DateTimeImmutable $now):MessageRecord{$t=$this->table(TableName::MESSAGES);$ts=$this->ts($now);$affected=$this->database->execute("UPDATE {$t} SET delivery_status='retry_pending',message_revision=message_revision+1,queued_at=%s,processing_at=NULL,updated_at=%s WHERE event_id=%d AND message_id=%d AND message_revision=%d AND delivery_status IN ('failed','uncertain','bounced')",[$ts,$ts,$s->eventId,$current->messageId,$current->revision]);if($affected!==1)throw new CommunicationException('resource_modified');return new MessageRecord($current->messageId,$current->campaignId,$current->logicalKey,$current->recipientAddress,$current->subject,$current->content,$current->channel,'retry_pending',$current->revision+1,$current->invitationId,$current->attendeeId,$current->recipientName,$current->plainText,$current->provider,$current->providerMessageId,$current->attemptCount,$now,null,$current->providerAcceptedAt,$current->deliveredAt,$current->failedAt,$current->bouncedAt,$current->cancelledAt,$current->createdAt,$now);}
    private function template(array $r):TemplateRecord{return new TemplateRecord((int)$r['template_id'],(string)$r['template_key'],(string)$r['template_name'],CommunicationChannel::from($r['channel']),(int)$r['version_number'],(string)$r['template_status'],$r['subject_template']===null?null:(string)$r['subject_template'],(string)$r['body_template'],$r['plain_text_template']===null?null:(string)$r['plain_text_template'],json_decode((string)($r['allowed_merge_fields']??'[]'),true,32,JSON_THROW_ON_ERROR),(string)($r['template_type']??'general'),(int)($r['template_revision']??1));}
    private function templateRecord(EventScope $scope,int $templateId,bool $lock):?TemplateRecord{$table=$this->table(TableName::COMMUNICATION_TEMPLATES);$row=$this->database->fetchRow('SELECT '.$this->accessColumns()." FROM {$table} WHERE event_id=%d AND template_id=%d AND deleted_at IS NULL LIMIT 1".($lock?' FOR UPDATE':''),[$scope->eventId,$templateId]);return $row===null?null:$this->accessTemplate($row);}
    private function campaignRecord(EventScope $scope,int $id,bool $lock):?CampaignRecord{$t=$this->table(TableName::CAMPAIGNS);$row=$this->database->fetchRow('SELECT '.$this->campaignColumns()." FROM {$t} WHERE event_id=%d AND campaign_id=%d AND deleted_at IS NULL LIMIT 1".($lock?' FOR UPDATE':''),[$scope->eventId,$id]);return$row===null?null:$this->campaign($row);}
    private function messageRecord(EventScope $scope,int $id,bool $lock):?MessageRecord{$t=$this->table(TableName::MESSAGES);$row=$this->database->fetchRow('SELECT '.$this->messageColumns()." FROM {$t} WHERE event_id=%d AND message_id=%d LIMIT 1".($lock?' FOR UPDATE':''),[$scope->eventId,$id]);return$row===null?null:$this->message($row);}
    private function messageColumns():string{return'message_id,campaign_id,idempotency_key,recipient_address,subject,rendered_content,channel,delivery_status,message_revision,invitation_id,attendee_id,recipient_name,plain_text_content,provider,provider_message_id,attempt_count,queued_at,processing_at,provider_accepted_at,delivered_at,failed_at,bounced_at,cancelled_at,created_at,updated_at';}
    private function message(array$r):MessageRecord{return new MessageRecord((int)$r['message_id'],$r['campaign_id']===null?null:(int)$r['campaign_id'],(string)$r['idempotency_key'],(string)$r['recipient_address'],$r['subject']===null?null:(string)$r['subject'],(string)$r['rendered_content'],CommunicationChannel::from($r['channel']),(string)$r['delivery_status'],(int)$r['message_revision'],$r['invitation_id']===null?null:(int)$r['invitation_id'],$r['attendee_id']===null?null:(int)$r['attendee_id'],$r['recipient_name']===null?null:(string)$r['recipient_name'],$r['plain_text_content']===null?null:(string)$r['plain_text_content'],$r['provider']===null?null:(string)$r['provider'],$r['provider_message_id']===null?null:(string)$r['provider_message_id'],(int)$r['attempt_count'],$this->date($r['queued_at']),$this->date($r['processing_at']),$this->date($r['provider_accepted_at']),$this->date($r['delivered_at']),$this->date($r['failed_at']),$this->date($r['bounced_at']),$this->date($r['cancelled_at']),$this->date($r['created_at']),$this->date($r['updated_at']));}
    private function campaignColumns():string{return'campaign_id,template_id,campaign_name,channel,campaign_type,campaign_status,campaign_revision,audience_definition,scheduled_at,started_at,completed_at,cancelled_at,audience_snapshot_count';}
    private function campaign(array$r):CampaignRecord{$a=json_decode((string)$r['audience_definition'],true,32,JSON_THROW_ON_ERROR);return new CampaignRecord((int)$r['campaign_id'],(int)$r['template_id'],(string)$r['campaign_name'],CommunicationChannel::from($r['channel']),CampaignPurpose::from($r['campaign_type']),AudienceMode::from($a['mode']??'dynamic'),$a,(string)$r['campaign_status'],(int)$r['campaign_revision'],$this->date($r['scheduled_at']),$this->date($r['started_at']),$this->date($r['completed_at']),$this->date($r['cancelled_at']),(int)($r['audience_snapshot_count']??0));}
    private function accessColumns():string{return 'template_id,template_key,template_name,channel,template_type,template_status,version_number,template_revision,subject_template,body_template,plain_text_template,allowed_merge_fields,created_at,updated_at,published_at,archived_at';}
    private function accessTemplate(array $r):TemplateRecord{return new TemplateRecord((int)$r['template_id'],(string)$r['template_key'],(string)$r['template_name'],CommunicationChannel::from($r['channel']),(int)$r['version_number'],(string)$r['template_status'],$r['subject_template']===null?null:(string)$r['subject_template'],(string)$r['body_template'],$r['plain_text_template']===null?null:(string)$r['plain_text_template'],json_decode((string)($r['allowed_merge_fields']??'[]'),true,32,JSON_THROW_ON_ERROR),(string)$r['template_type'],(int)$r['template_revision'],$this->date($r['created_at']),$this->date($r['updated_at']),$this->date($r['published_at']),$this->date($r['archived_at']));}
    private function nullable(mixed $value,string $placeholder,array &$parameters):string{if($value===null)return 'NULL';$parameters[]=$value;return $placeholder;}
    private function date(mixed $value):?DateTimeImmutable{return $value===null?null:new DateTimeImmutable((string)$value,new DateTimeZone('UTC'));}
    private function ts(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}
}
