<?php
namespace EventFlow\Infrastructure\Persistence\WordPress;
use DateTimeImmutable;use DateTimeZone;
use EventFlow\Application\CheckIn\{CheckInAction,CheckInException,CheckInMethod,CheckInRepository,CheckInStation,ReceptionAttendee};
use EventFlow\Application\Persistence\EventScope;use EventFlow\Infrastructure\Persistence\{PersistenceException,TableName};
final class WpdbCheckInRepository extends AbstractWpdbRepository implements CheckInRepository
{
    public function createStation(EventScope $s,string $name,?string $code,?int $actor,DateTimeImmutable $now):CheckInStation{$t=$this->table(TableName::CHECKIN_STATIONS);$ts=$this->ts($now);$sql="INSERT INTO {$t} (event_id,station_name,station_code,station_type,station_status,sort_order,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%s,".($code===null?'NULL':'%s').",%s,%s,%d,".($actor===null?'NULL,NULL':'%d,%d').",%s,%s)";$p=[$s->eventId,$name];if($code!==null)$p[]=$code;array_push($p,'staffed','active',100);if($actor!==null){$p[]=$actor;$p[]=$actor;}array_push($p,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('checkin_station_create_failed');return new CheckInStation($this->database->lastInsertId(),$name,$code);}
    public function search(EventScope $s,string $q,int $limit):array{$like='%'.$this->database->escapeLike($q).'%';return $this->projection($s,"a.display_name LIKE %s",[$like],$limit,false);}
    public function lookup(EventScope $s,string $code):?ReceptionAttendee{$rows=$this->projection($s,"SHA2(CONCAT('eventflow-reception-v1:', a.event_id, ':', a.attendee_id), 256) = %s",[$code],1,false);return $rows[0]??null;}
    public function lockAttendees(EventScope $s,array $ids):array{$ph=implode(',',array_fill(0,count($ids),'%d'));return $this->projection($s,"a.attendee_id IN ({$ph})",$ids,count($ids),true);}
    public function lockStation(EventScope $s,int $id):?CheckInStation{$t=$this->table(TableName::CHECKIN_STATIONS);$r=$this->database->fetchRow("SELECT station_id,station_name,station_code FROM {$t} WHERE event_id=%d AND station_id=%d AND station_status=%s AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$s->eventId,$id,'active']);return $r===null?null:new CheckInStation((int)$r['station_id'],(string)$r['station_name'],$r['station_code']===null?null:(string)$r['station_code']);}
    public function append(EventScope $s,int $attendeeId,CheckInMethod $method,?int $stationId,?int $reversalOf,?string $operationId,?string $reason,?string $notes,?int $actor,DateTimeImmutable $now):CheckInAction{$t=$this->table(TableName::CHECKINS);$type=$reversalOf===null?'check_in':'reversal';$ts=$this->ts($now);$cols=['event_id','attendee_id','station_id','action_type','checkin_method','reversal_of_checkin_id','performed_by_user_id','operation_id','reason','notes','occurred_at','created_at'];$vals=['%d','%d',$stationId===null?'NULL':'%d','%s','%s',$reversalOf===null?'NULL':'%d',$actor===null?'NULL':'%d',$operationId===null?'NULL':'%s',$reason===null?'NULL':'%s',$notes===null?'NULL':'%s','%s','%s'];$p=[$s->eventId,$attendeeId];foreach([[$stationId,'int'],[$type,'str'],[$method->value,'str'],[$reversalOf,'int'],[$actor,'int'],[$operationId,'str'],[$reason,'str'],[$notes,'str'],[$ts,'str'],[$ts,'str']]as[$v,$x])if($v!==null)$p[]=$v;if($this->database->execute("INSERT INTO {$t} (".implode(',',$cols).') VALUES ('.implode(',',$vals).')',$p)!==1)throw new PersistenceException('checkin_append_failed');return new CheckInAction($this->database->lastInsertId(),$attendeeId,$type,$method,$stationId,$reversalOf,$operationId,$now);}
    public function lockAction(EventScope $s,int $id):?CheckInAction{$t=$this->table(TableName::CHECKINS);$r=$this->database->fetchRow("SELECT checkin_id,attendee_id,action_type,checkin_method,station_id,reversal_of_checkin_id,operation_id,occurred_at FROM {$t} WHERE event_id=%d AND checkin_id=%d LIMIT 1 FOR UPDATE",[$s->eventId,$id]);return $r===null?null:$this->action($r);}
    public function reversalExists(EventScope $s,int $id):bool{$t=$this->table(TableName::CHECKINS);return $this->database->fetchValue("SELECT checkin_id FROM {$t} WHERE event_id=%d AND reversal_of_checkin_id=%d AND action_type=%s LIMIT 1 FOR UPDATE",[$s->eventId,$id,'reversal'])!==null;}
    private function projection(EventScope $s,string $predicate,array $params,int $limit,bool $lock):array{$a=$this->table(TableName::ATTENDEES);$x=$this->table(TableName::SEATING_ASSIGNMENTS);$t=$this->table(TableName::TABLES);$se=$this->table(TableName::SEATS);$c=$this->table(TableName::CHECKINS);$sql="SELECT a.attendee_id,a.display_name,a.attendance_status,t.table_name,se.seat_label,ci.checkin_id AS active_checkin_id,SHA2(CONCAT('eventflow-reception-v1:',a.event_id,':',a.attendee_id),256) AS lookup_code FROM {$a} a LEFT JOIN {$x} x ON x.event_id=a.event_id AND x.attendee_id=a.attendee_id AND x.assignment_status='active' LEFT JOIN {$t} t ON t.event_id=x.event_id AND t.table_id=x.table_id LEFT JOIN {$se} se ON se.event_id=x.event_id AND se.seat_id=x.seat_id LEFT JOIN {$c} ci ON ci.checkin_id=(SELECT MAX(c1.checkin_id) FROM {$c} c1 WHERE c1.event_id=a.event_id AND c1.attendee_id=a.attendee_id AND c1.action_type='check_in' AND NOT EXISTS (SELECT 1 FROM {$c} r WHERE r.event_id=c1.event_id AND r.reversal_of_checkin_id=c1.checkin_id AND r.action_type='reversal')) WHERE a.event_id=%d AND a.deleted_at IS NULL AND {$predicate} ORDER BY a.attendee_id ASC LIMIT %d".($lock?' FOR UPDATE':'');$rows=$this->database->fetchAll($sql,[$s->eventId,...$params,$limit]);return array_map(fn($r)=>new ReceptionAttendee((int)$r['attendee_id'],(string)$r['display_name'],(string)$r['attendance_status'],$r['table_name']===null?null:(string)$r['table_name'],$r['seat_label']===null?null:(string)$r['seat_label'],$r['active_checkin_id']!==null,$r['active_checkin_id']===null?null:(int)$r['active_checkin_id'],(string)$r['lookup_code']),$rows);}
    private function action(array $r):CheckInAction{$m=CheckInMethod::tryFrom((string)$r['checkin_method'])??throw new PersistenceException('checkin_method_invalid');return new CheckInAction((int)$r['checkin_id'],(int)$r['attendee_id'],(string)$r['action_type'],$m,$r['station_id']===null?null:(int)$r['station_id'],$r['reversal_of_checkin_id']===null?null:(int)$r['reversal_of_checkin_id'],$r['operation_id']===null?null:(string)$r['operation_id'],new DateTimeImmutable((string)$r['occurred_at'],new DateTimeZone('UTC')));}
    private function ts(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}
}
