<?php

namespace EventFlow\Infrastructure\Persistence\WordPress;

use DateTimeImmutable;
use DateTimeZone;
use EventFlow\Application\Communication\AudienceMode;
use EventFlow\Application\Communication\CampaignPurpose;
use EventFlow\Application\Communication\CampaignRecord;
use EventFlow\Application\Communication\CampaignRecipient;
use EventFlow\Application\Communication\CommunicationChannel;
use EventFlow\Application\Communication\CommunicationException;
use EventFlow\Application\Communication\CommunicationRepository;
use EventFlow\Application\Communication\MessageRecord;
use EventFlow\Application\Communication\TemplateRecord;
use EventFlow\Application\Persistence\EventScope;
use EventFlow\Infrastructure\Persistence\PersistenceException;
use EventFlow\Infrastructure\Persistence\TableName;

final class WpdbCommunicationRepository extends AbstractWpdbRepository implements CommunicationRepository
{
    public function createDraft(EventScope $scope, string $key, string $name, CommunicationChannel $channel, string $type, ?string $subject, string $body, ?string $plainText, array $allowedFields, ?int $actor, DateTimeImmutable $now): TemplateRecord
    {
        $table=$this->table(TableName::COMMUNICATION_TEMPLATES);$latest=$this->database->fetchRow("SELECT version_number FROM {$table} WHERE event_id=%d AND template_key=%s AND channel=%s AND deleted_at IS NULL ORDER BY version_number DESC LIMIT 1 FOR UPDATE",[$scope->eventId,$key,$channel->value]);$version=((int)($latest['version_number']??0))+1;$ts=$this->ts($now);
        $sql="INSERT INTO {$table} (event_id,template_key,template_name,channel,template_type,template_status,version_number,subject_template,body_template,plain_text_template,allowed_merge_fields,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%s,%s,%s,%s,'draft',%d,".($subject===null?'NULL':'%s').",%s,".($plainText===null?'NULL':'%s').",%s,".($actor===null?'NULL,NULL':'%d,%d').",%s,%s)";$p=[$scope->eventId,$key,$name,$channel->value,$type,$version];if($subject!==null)$p[]=$subject;$p[]=$body;if($plainText!==null)$p[]=$plainText;$p[]=json_encode($allowedFields,JSON_THROW_ON_ERROR);if($actor!==null){$p[]=$actor;$p[]=$actor;}array_push($p,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('template_create_failed');return new TemplateRecord($this->database->lastInsertId(),$key,$name,$channel,$version,'draft',$subject,$body,$plainText,$allowedFields);
    }
    public function publish(EventScope $scope,int $templateId,?int $actor,DateTimeImmutable $now):TemplateRecord{$t=$this->table(TableName::COMMUNICATION_TEMPLATES);$r=$this->database->fetchRow("SELECT template_id,template_key,template_name,channel,version_number,template_status,subject_template,body_template,plain_text_template,allowed_merge_fields FROM {$t} WHERE event_id=%d AND template_id=%d AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$scope->eventId,$templateId]);if($r===null)throw new CommunicationException('resource_not_found');if($r['template_status']!=='draft')throw new CommunicationException('template_immutable');$ts=$this->ts($now);$sql="UPDATE {$t} SET template_status='published',published_at=%s,updated_by_user_id=".($actor===null?'NULL':'%d').",updated_at=%s WHERE event_id=%d AND template_id=%d AND template_status='draft'";$p=[$ts];if($actor!==null)$p[]=$actor;array_push($p,$ts,$scope->eventId,$templateId);if($this->database->execute($sql,$p)!==1)throw new CommunicationException('resource_modified');$r['template_status']='published';return $this->template($r);}
    public function createCampaign(EventScope $scope,int $templateId,string $name,CommunicationChannel $channel,CampaignPurpose $purpose,AudienceMode $mode,array $audience,?int $actor,DateTimeImmutable $now):CampaignRecord{$this->lockPublishedTemplate($scope,$templateId)??throw new CommunicationException('campaign_template_invalid');if($mode===AudienceMode::SNAPSHOT&&$audience['invitation_ids']===[]){$i=$this->table(TableName::INVITATIONS);$audience['invitation_ids']=array_map('intval',$this->database->fetchAll("SELECT invitation_id FROM {$i} WHERE event_id=%d AND invitation_status='active' AND deleted_at IS NULL ORDER BY invitation_id FOR UPDATE",[$scope->eventId]));}$t=$this->table(TableName::CAMPAIGNS);$ts=$this->ts($now);$json=json_encode($audience,JSON_THROW_ON_ERROR);$sql="INSERT INTO {$t} (event_id,template_id,campaign_name,channel,campaign_type,campaign_status,audience_definition,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES (%d,%d,%s,%s,%s,'draft',%s,".($actor===null?'NULL,NULL':'%d,%d').",%s,%s)";$p=[$scope->eventId,$templateId,$name,$channel->value,$purpose->value,$json];if($actor!==null){$p[]=$actor;$p[]=$actor;}array_push($p,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('campaign_create_failed');return new CampaignRecord($this->database->lastInsertId(),$templateId,$name,$channel,$purpose,$mode,$audience,'draft');}
    public function lockCampaign(EventScope $s,int $id):?CampaignRecord{$t=$this->table(TableName::CAMPAIGNS);$r=$this->database->fetchRow("SELECT campaign_id,template_id,campaign_name,channel,campaign_type,campaign_status,audience_definition FROM {$t} WHERE event_id=%d AND campaign_id=%d AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$s->eventId,$id]);if($r===null)return null;$a=json_decode((string)$r['audience_definition'],true,32,JSON_THROW_ON_ERROR);return new CampaignRecord((int)$r['campaign_id'],(int)$r['template_id'],(string)$r['campaign_name'],CommunicationChannel::from($r['channel']),CampaignPurpose::from($r['campaign_type']),AudienceMode::from($a['mode']??'dynamic'),$a,(string)$r['campaign_status']);}
    public function lockPublishedTemplate(EventScope $s,int $id):?TemplateRecord{$t=$this->table(TableName::COMMUNICATION_TEMPLATES);$r=$this->database->fetchRow("SELECT template_id,template_key,template_name,channel,version_number,template_status,subject_template,body_template,plain_text_template,allowed_merge_fields FROM {$t} WHERE event_id=%d AND template_id=%d AND template_status='published' AND deleted_at IS NULL LIMIT 1 FOR UPDATE",[$s->eventId,$id]);return $r===null?null:$this->template($r);}
    public function resolveRecipients(EventScope $s,CampaignRecord $c):array{$ids=$c->audienceDefinition['invitation_ids']??[];$where=$ids===[]?'':(' AND i.invitation_id IN ('.implode(',',array_fill(0,count($ids),'%d')).')');$i=$this->table(TableName::INVITATIONS);$a=$this->table(TableName::ATTENDEES);if(($c->audienceDefinition['filter']??'')==='confirmed_attendees'){$rows=$this->database->fetchAll("SELECT i.invitation_id,a.attendee_id,a.display_name,COALESCE(a.email,i.email) address FROM {$a} a JOIN {$i} i ON i.event_id=a.event_id AND i.invitation_id=a.invitation_id WHERE a.event_id=%d AND a.attendance_status='confirmed' AND a.deleted_at IS NULL{$where} ORDER BY a.attendee_id",[$s->eventId,...$ids]);}else{$rows=$this->database->fetchAll("SELECT i.invitation_id,NULL attendee_id,i.primary_name display_name,i.email address FROM {$i} i WHERE i.event_id=%d AND i.invitation_status='active' AND i.email IS NOT NULL AND i.deleted_at IS NULL{$where} ORDER BY i.invitation_id",[$s->eventId,...$ids]);}return array_map(static fn($r)=>new CampaignRecipient((int)$r['invitation_id'],$r['attendee_id']===null?null:(int)$r['attendee_id'],(string)$r['display_name'],(string)$r['address'],['recipient_name'=>(string)$r['display_name'],'guest_link'=>'']),$rows);}
    public function createOrFindMessage(EventScope $s,CampaignRecord $c,CampaignRecipient $r,string $key,?string $subject,string $body,?string $plain,DateTimeImmutable $now):MessageRecord{$t=$this->table(TableName::MESSAGES);$existing=$this->database->fetchRow("SELECT message_id,campaign_id,idempotency_key,recipient_address,subject,rendered_content FROM {$t} WHERE idempotency_key=%s LIMIT 1 FOR UPDATE",[$key]);if($existing!==null)return new MessageRecord((int)$existing['message_id'],(int)$existing['campaign_id'],$key,(string)$existing['recipient_address'],$existing['subject'],(string)$existing['rendered_content']);$ts=$this->ts($now);$sql="INSERT INTO {$t} (event_id,campaign_id,invitation_id,attendee_id,channel,recipient_name,recipient_address,recipient_address_normalized,subject,rendered_content,plain_text_content,delivery_status,idempotency_key,queued_at,created_at,updated_at) VALUES (%d,%d,%d,".($r->attendeeId===null?'NULL':'%d').",%s,%s,%s,%s,".($subject===null?'NULL':'%s').",%s,".($plain===null?'NULL':'%s').",'queued',%s,%s,%s,%s)";$p=[$s->eventId,$c->campaignId,$r->invitationId];if($r->attendeeId!==null)$p[]=$r->attendeeId;array_push($p,$c->channel->value,$r->name,$r->address,strtolower($r->address));if($subject!==null)$p[]=$subject;$p[]=$body;if($plain!==null)$p[]=$plain;array_push($p,$key,$ts,$ts,$ts);if($this->database->execute($sql,$p)!==1)throw new PersistenceException('message_create_failed');return new MessageRecord($this->database->lastInsertId(),$c->campaignId,$key,$r->address,$subject,$body);}
    public function freezeQueued(EventScope $s,CampaignRecord $c,int $count,DateTimeImmutable $now):void{$t=$this->table(TableName::CAMPAIGNS);$ts=$this->ts($now);if($this->database->execute("UPDATE {$t} SET campaign_status='queued',audience_snapshot_count=%d,queued_count=%d,started_at=%s,updated_at=%s WHERE event_id=%d AND campaign_id=%d AND campaign_status IN ('draft','scheduled')",[$count,$count,$ts,$ts,$s->eventId,$c->campaignId])!==1)throw new CommunicationException('campaign_already_queued');}
    private function template(array $r):TemplateRecord{return new TemplateRecord((int)$r['template_id'],(string)$r['template_key'],(string)$r['template_name'],CommunicationChannel::from($r['channel']),(int)$r['version_number'],(string)$r['template_status'],$r['subject_template']===null?null:(string)$r['subject_template'],(string)$r['body_template'],$r['plain_text_template']===null?null:(string)$r['plain_text_template'],json_decode((string)($r['allowed_merge_fields']??'[]'),true,32,JSON_THROW_ON_ERROR));}
    private function ts(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');}
}
