<?php
namespace EventFlow\Application\Export;
use DateInterval;use Throwable;use EventFlow\Application\Audit\{AuditAction,AuditEntityType,AuditEvent,AuditService};use EventFlow\Application\Authorization\{AuthorizationService,Capability,PrincipalContext,PrincipalType};use EventFlow\Application\Clock\Clock;use EventFlow\Application\Idempotency\{IdempotencyOutcome,IdempotencyResultReference,IdempotencyService,IdempotentOperationResult};use EventFlow\Application\Job\{JobRecord,JobRepository,JobRequest};use EventFlow\Application\Persistence\EventScope;use EventFlow\Application\Transaction\TransactionManager;
final readonly class ExportService
{
 public function __construct(private ExportRepository $repository,private ExportDataSource $data,private ExportArtifactStorage $storage,private JobRepository $jobs,private AuthorizationService $authorization,private IdempotencyService $idempotency,private AuditService $audit,private Clock $clock,private TransactionManager $transactions,private int $maxConcurrentPerEvent=2){}
 public function request(PrincipalContext $principal,EventScope $scope,ExportType $type,ExportFormat $format,string $purpose,string $key):IdempotencyOutcome{$purpose=trim($purpose);if($purpose===''||strlen($purpose)>500)throw new ExportException('export_purpose_required');return $this->idempotency->execute($principal,$scope,'export.request',$key,['type'=>$type->value,'format'=>$format->value,'purpose'=>$purpose,'temporal_mode'=>'requested_at_snapshot'],function()use($principal,$scope,$type,$format,$purpose){$cap=$type->containsPii()?Capability::EXPORT_PII:Capability::VIEW_REPORTS;$this->authorization->requireEventCapability($principal,$scope,$cap);$now=$this->clock->now();$export=$this->repository->create($scope,$type,$format,$purpose,$now,$now->add(new DateInterval('PT24H')),$this->actor($principal),$now);$this->jobs->enqueue(JobRequest::create($scope,'export.generate',1,['export_id'=>$export->exportId,'type'=>$type->value,'format'=>$format->value,'cutoff_at'=>$now->format(DATE_ATOM)],[$cap],$now,100,5,'export:'.$export->exportId),$now);$this->audit->recordRequired(new AuditEvent($principal,$scope,AuditAction::EXPORT_REQUESTED,AuditEntityType::EXPORT,$export->exportId,after:['type'=>$type->value,'format'=>$format->value,'contains_pii'=>$type->containsPii(),'temporal_mode'=>'requested_at_snapshot'],reason:$purpose));return new IdempotentOperationResult(new IdempotencyResultReference('export',$export->exportId,202),$export);});}
 public function generate(JobRecord $job):ExportRecord{if($job->jobType!=='export.generate'||$job->eventScope===null)throw new ExportException('export_job_invalid');$id=(int)($job->payload['export_id']??0);$export=$this->transactions->transactional(fn()=>$this->repository->beginGeneration($job->eventScope,$id,$this->maxConcurrentPerEvent,$this->clock->now()));try{$artifact=$this->storage->publish($export,$this->data->rows($export));try{return $this->transactions->transactional(function()use($job,$export,$artifact){$ready=$this->repository->markReady($export,$artifact,$this->clock->now());$this->audit->recordRequired(new AuditEvent($job->principal(),$export->eventScope,AuditAction::EXPORT_READY,AuditEntityType::EXPORT,$export->exportId,after:['sha256'=>$artifact->sha256,'size_bytes'=>$artifact->sizeBytes]));return $ready;});}catch(Throwable $e){$this->storage->delete($artifact->locator);throw $e;}}catch(Throwable $e){$code=$e instanceof ExportException?$e->safeCode:'export_generation_failed';$this->transactions->transactional(fn()=>$this->repository->markFailed($export,$code,$this->clock->now()));throw $e;}}
 public function authorizeDownload(PrincipalContext $principal,EventScope $scope,int $exportId):ExportDownloadGrant{return $this->transactions->transactional(function()use($principal,$scope,$exportId){$export=$this->repository->lock($scope,$exportId)??throw new ExportException('resource_not_found');$this->authorization->requireEventCapability($principal,$scope,$export->containsPii?Capability::EXPORT_PII:Capability::VIEW_REPORTS);if($export->status!=='ready'||$export->expiresAt<=$this->clock->now()||$export->artifactLocator===null||$export->artifactHash===null||$export->mimeType===null||$export->sizeBytes===null)throw new ExportException('export_not_downloadable');$this->repository->recordDownload($export,$this->clock->now());$this->audit->recordRequired(new AuditEvent($principal,$scope,AuditAction::EXPORT_DOWNLOADED,AuditEntityType::EXPORT,$exportId,after:['contains_pii'=>$export->containsPii]));return new ExportDownloadGrant($exportId,$export->artifactLocator,$export->mimeType,'eventflow-'.$export->type->value.'-'.$exportId.'.'.$export->format->value,$export->artifactHash,$export->sizeBytes);});}
 private function actor(PrincipalContext $p):?int{return $p->type===PrincipalType::WORDPRESS_USER?$p->userId:null;}
}
