<?php
namespace EventFlow\Tests\Unit\Application\CheckIn;
use DateTimeImmutable;use DateTimeZone;use PHPUnit\Framework\TestCase;
use EventFlow\Application\CheckIn\{BulkCheckInResult,CheckInAction,CheckInException,CheckInMethod,CheckInRepository,CheckInService,CheckInStation,ReceptionAttendee,ReceptionLookupCode};
use EventFlow\Application\Audit\{AuditCanonicalizer,AuditPayloadRedactor,AuditRecord,AuditRepository,AuditService};
use EventFlow\Application\Authorization\{AuthorizationService,EventRole,GlobalRecoveryAuthority,MembershipReader,MembershipSnapshot,PrincipalContext,RoleCapabilityPolicy};
use EventFlow\Application\Clock\Clock;use EventFlow\Application\Persistence\EventScope;use EventFlow\Application\Security\SecureRandom;use EventFlow\Application\Transaction\{TransactionManager,TransactionOptions};
use EventFlow\Application\Idempotency\{CanonicalRequestHasher,IdempotencyClaimResult,IdempotencyClaimState,IdempotencyRecord,IdempotencyRepository,IdempotencyRequest,IdempotencyResultReference,IdempotencyService};
final class CheckInServiceTest extends TestCase
{
 public function testDedicatedLookupCodeIsStableAndEventScoped():void{self::assertSame(hash('sha256','eventflow-reception-v1:9:1'),ReceptionLookupCode::for(new EventScope(9),1));self::assertNotSame(ReceptionLookupCode::for(new EventScope(9),1),ReceptionLookupCode::for(new EventScope(10),1));}
 public function testLeastPrivilegeSearchContainsOnlyReceptionProjection():void{$f=new CIFixture();$r=$f->service->search($f->principal,$f->scope,'Guest');self::assertCount(2,$r);self::assertSame('Table 1',$r[0]->tableName);self::assertObjectNotHasProperty('email',$r[0]);}
 public function testBulkIsAtomicSortedAndIdempotent():void{$f=new CIFixture();$o=$f->service->bulk($f->principal,$f->scope,[2,1],1,CheckInMethod::GUEST_LIST,'bulk-key-001')->response;self::assertInstanceOf(BulkCheckInResult::class,$o);self::assertSame([1,2],array_map(fn($a)=>$a->attendeeId,$o->actions));self::assertSame($o->operationId,$o->actions[0]->operationId);$replay=$f->service->bulk($f->principal,$f->scope,[1,2],1,CheckInMethod::GUEST_LIST,'bulk-key-001');self::assertTrue($replay->replayed);self::assertCount(2,$f->repo->actions);}
 public function testAlreadyCheckedInRejectsWholeBulk():void{$f=new CIFixture();$f->repo->people[2]=$f->repo->people[2] = new ReceptionAttendee(2,'Guest Two','confirmed',null,null,true,8,str_repeat('b',64));try{$f->service->bulk($f->principal,$f->scope,[1,2],1,CheckInMethod::SEARCH,'bulk-fail');self::fail();}catch(CheckInException $e){self::assertSame('attendee_already_checked_in',$e->safeCode);}self::assertSame([],$f->repo->actions);}
 public function testReversalIsAdditiveRequiresReasonAndCannotRepeat():void{$f=new CIFixture();$f->repo->actions[8]=new CheckInAction(8,1,'check_in',CheckInMethod::SEARCH,1,null,null,$f->clock->now());try{$f->service->reverse($f->principal,$f->scope,8,'','reverse-key-000');self::fail();}catch(CheckInException $e){self::assertSame('checkin_reversal_reason_required',$e->safeCode);}$a=$f->service->reverse($f->principal,$f->scope,8,'Wrong guest','reverse-key-001')->response;self::assertSame('reversal',$a->actionType);self::assertSame(8,$a->reversalOf);try{$f->service->reverse($f->principal,$f->scope,8,'Again','reverse-key-002');self::fail();}catch(CheckInException $e){self::assertSame('checkin_already_reversed',$e->safeCode);}}
}
final class CIFixture{public EventScope $scope;public PrincipalContext $principal;public CIMemoryRepo $repo;public CheckInService $service;public CIClock $clock;public function __construct(){$this->scope=new EventScope(9);$this->principal=PrincipalContext::wordpressUser(7);$this->clock=new CIClock();$tx=new CITx();$this->repo=new CIMemoryRepo();$auth=new AuthorizationService(new CIMembers(),new RoleCapabilityPolicy(),$this->clock,new CINoRecovery());$idem=new IdempotencyService(new CIIdem(),$tx,$this->clock,new CIRandom(),new CanonicalRequestHasher());$audit=new AuditService(new CIAudit(),$tx,$this->clock,new AuditPayloadRedactor(),new AuditCanonicalizer());$this->service=new CheckInService($this->repo,$auth,$idem,$audit,$this->clock,new CIRandom());}}
final class CIMemoryRepo implements CheckInRepository{public array $people;public array $actions=[];private int $next=10;public function __construct(){$this->people=[1=>new ReceptionAttendee(1,'Guest One','confirmed','Table 1','A',false,null,str_repeat('a',64)),2=>new ReceptionAttendee(2,'Guest Two','confirmed',null,null,false,null,str_repeat('b',64))];}public function createStation(EventScope $s,string $n,?string $c,?int $a,DateTimeImmutable $d):CheckInStation{return new CheckInStation(1,$n,$c);}public function search(EventScope $s,string $q,int $l):array{return array_values($this->people);}public function lookup(EventScope $s,string $c):?ReceptionAttendee{foreach($this->people as $p)if($p->lookupCode===$c)return $p;return null;}public function lockAttendees(EventScope $s,array $ids):array{$r=[];foreach($ids as $id)if(isset($this->people[$id]))$r[]=$this->people[$id];return $r;}public function lockStation(EventScope $s,int $id):?CheckInStation{return $id===1?new CheckInStation(1,'Door','D1'):null;}public function append(EventScope $s,int $id,CheckInMethod $m,?int $st,?int $rev,?string $op,?string $reason,?string $notes,?int $actor,DateTimeImmutable $now):CheckInAction{$a=new CheckInAction($this->next++,$id,$rev===null?'check_in':'reversal',$m,$st,$rev,$op,$now);$this->actions[$a->checkInId]=$a;return $a;}public function lockAction(EventScope $s,int $id):?CheckInAction{return $this->actions[$id]??null;}public function reversalExists(EventScope $s,int $id):bool{foreach($this->actions as $a)if($a->reversalOf===$id)return true;return false;}}
final class CIMembers implements MembershipReader{public function findCurrent(EventScope $s,int $u):?MembershipSnapshot{return new MembershipSnapshot(1,$s,$u,EventRole::OWNER,false,null);}}final readonly class CINoRecovery implements GlobalRecoveryAuthority{public function canRecoverPrimaryOwnership(int $u):bool{return false;}}final readonly class CIClock implements Clock{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-16 21:00:00',new DateTimeZone('UTC'));}}final readonly class CIRandom implements SecureRandom{public function hex(int $b):string{return str_repeat('e',$b*2);}}final class CITx implements TransactionManager{private int $d=0;public function transactional(callable $o,?TransactionOptions $x=null):mixed{$this->d++;try{return $o();}finally{$this->d--;}}public function isActive():bool{return $this->d>0;}public function assertNotActive():void{}}
final class CIAudit implements AuditRepository{private array $r=[];public function lockChainHead(?EventScope $s):?string{return $this->r===[]?null:$this->r[array_key_last($this->r)]->recordHash;}public function append(AuditRecord $r):int{$this->r[]=$r;return count($this->r);}}
final class CIIdem implements IdempotencyRepository{private array $r=[];public function claim(IdempotencyRequest $q,string $l,DateTimeImmutable $n,DateTimeImmutable $le,DateTimeImmutable $re):IdempotencyClaimResult{$k=$q->operationName.bin2hex($q->keyDigest);if(isset($this->r[$k]))return new IdempotencyClaimResult(IdempotencyClaimState::REPLAY,$this->r[$k]);return new IdempotencyClaimResult(IdempotencyClaimState::ACQUIRED,$this->r[$k]=new IdempotencyRecord(count($this->r)+1,$q->requestFingerprint,'in_progress',$le,null,false));}public function complete(int $id,string $l,IdempotencyResultReference $ref,bool $s,DateTimeImmutable $at):void{foreach($this->r as $k=>$v)if($v->recordId===$id)$this->r[$k]=new IdempotencyRecord($id,$v->requestFingerprint,'completed',null,$ref,$s);}public function fail(int $id,string $l,DateTimeImmutable $at):void{foreach($this->r as $k=>$v)if($v->recordId===$id)unset($this->r[$k]);}}
